[package]
name = "collomatique-constraints-groups"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
collomatique-state-colloscopes = { path = "../state-colloscopes" }
collomatique-ilp = { path = "../ilp" }
collomatique-ilp-modeler = { path = "../ilp-modeler" }
thiserror.workspace = true

[dev-dependencies]
collomatique-storage = { path = "../storage" }
collomatique-state = { path = "../state" }
collomatique-testgen-colloscopes = { path = "../testgen-colloscopes" }
