[package]
name = "collomatique-strategies"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
collomatique-ilp = { path = "../ilp", features = ["serde"] }
collomatique-ilp-modeler = { path = "../ilp-modeler", features = ["serde"] }
async-trait.workspace = true
futures.workspace = true
thiserror.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
