[package]
name = "collomatique-solver-colloscopes"
version = "0.1.0"
edition = "2021"

[dependencies]
collomatique-ilp = { path = "../ilp" }
collomatique-solver = { path = "../solver" }
collomatique-time = { path = "../time" }
ordered-float = "4.2.0"
thiserror = "1.0"
