//! Colloscopes state crate
//!
//! This crate implements the various concepts of [collomatique-state]
//! and the various traits for the specific case of colloscope representation.
//!

use serde::{Deserialize, Serialize};
use thiserror::Error;

use collomatique_state::{InMemoryData, Operation, tools};
use std::collections::BTreeMap;
use std::collections::BTreeSet;

/// Internal re-export of the generic table containers.
///
/// Tables are an implementation detail of this crate: consumers read them
/// through the inherent read API (`get`/`contains`/`iter`/`keys`/`values`/
/// `get_at`/…) and build their own copy with an explicit
/// `.iter().map(…).collect()` into a plain `BTreeMap`/`Vec` when they need one.
/// Kept `pub(crate)` so the path does not leak.
pub(crate) use collomatique_state::{OrderedTable, Table};

pub mod ids;
use ids::Id;
use ids::IdIssuer;
pub use ids::{
    GroupListId, IncompatId, NewId, PairingRuleId, PeriodId, SlotId, SlotPairingRuleId, StudentId,
    SubjectId, TeacherId, WeekId, WeekPatternId,
};
pub mod ops;
pub use ops::{
    AnnotatedOp, AssignmentOp, BalancingOp, ColloscopeOp, ExportConfigOp, GroupListOp, IncompatOp,
    Op, PairingOp, PeriodOp, SettingsOp, SlotOp, SlotPairingOp, StudentOp, SubjectOp, TeacherOp,
    WeekOp, WeekPatternOp,
};
pub use subjects::{
    Subject, SubjectInterrogationParameters, SubjectParameters, SubjectPeriodicity,
};

pub mod assignments;
pub mod balancing;
pub mod colloscope_params;
pub mod colloscopes;
pub mod export_config;
pub mod group_lists;
pub mod incompats;
pub mod invariants;
pub mod non_empty_range;
pub mod pairings;
pub mod periods;
pub mod refs;
pub mod settings;
pub mod slot_pairings;
pub mod slots;
pub mod soft_param;
pub mod students;
pub mod subjects;
pub mod teachers;
pub mod week_patterns;
pub mod weeks;

pub use assignments::AssignmentError;
pub use balancing::BalancingError;
pub use colloscope_params::InvariantError;
pub use colloscopes::ColloscopeError;
pub use export_config::ExportConfigError;
pub use group_lists::GroupListError;
pub use incompats::IncompatError;
pub use invariants::{Convergence, FixableInvariant, LogicError};
pub use non_empty_range::{EmptyRangeError, NonEmptyRangeInclusive};
pub use pairings::PairingError;
pub use periods::PeriodError;
pub use settings::SettingsError;
pub use slot_pairings::SlotPairingError;
pub use slots::SlotError;
pub use students::StudentError;
pub use subjects::SubjectError;
pub use teachers::TeacherError;
pub use week_patterns::WeekPatternError;
pub use weeks::WeekError;

// Per-domain precheck error enums for [Data::force_apply] — the carve-out
// subset of each domain's error surface (step-3 survey Table 2). Introduced in
// step 4; this is the error vocabulary that survives step 5.
pub use assignments::AssignmentPrecheckError;
pub use balancing::BalancingPrecheckError;
pub use colloscopes::ColloscopePrecheckError;
pub use export_config::ExportConfigPrecheckError;
pub use group_lists::GroupListPrecheckError;
pub use incompats::IncompatPrecheckError;
pub use pairings::PairingPrecheckError;
pub use periods::PeriodPrecheckError;
pub use settings::SettingsPrecheckError;
pub use slot_pairings::SlotPairingPrecheckError;
pub use slots::SlotPrecheckError;
pub use students::StudentPrecheckError;
pub use subjects::SubjectPrecheckError;
pub use teachers::TeacherPrecheckError;
pub use week_patterns::WeekPatternPrecheckError;
pub use weeks::WeekPrecheckError;

pub use refs::{
    GroupListRefSite, PeriodRefSite, RefVisitor, Reference, SlotRefSite, StudentRefSite,
    SubjectRefSite, TeacherRefSite, WeekPatternRefSite, WeekRefSite,
};

// Joined views generated by `#[derive(Join)]` on the entity structs — the
// reference-based read shape (every FK resolved to a borrow of its entity).
pub use incompats::JoinedIncompatibility;
pub use pairings::{JoinedPairingRule, JoinedRulePart};
pub use slot_pairings::{JoinedSlotPairingRule, JoinedSlotRulePart};
pub use slots::JoinedSlot;
pub use students::JoinedStudent;
pub use subjects::JoinedSubject;
pub use teachers::JoinedTeacher;

/// Description of a person with contacts
///
/// This type is used to describe both students and teachers.
/// Each student and teacher has its own card with name and contacts.
/// There are not used for the colloscope solving process
/// but can help produce a nice colloscope output with contact info.
#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct PersonWithContact {
    /// Surname of the person
    ///
    /// Though this field can be an empty string,
    /// it is considered mandatory internally
    pub surname: String,

    /// Firstname of the person
    ///
    /// Though this field can be an empty string,
    /// it is considered mandatory internally
    pub firstname: String,

    /// Person's telephone number
    ///
    /// This field is optional: this reflects the
    /// fact that some persons might not want to share
    /// their personal info or only some of it.
    pub tel: Option<non_empty_string::NonEmptyString>,

    /// Person's email
    ///
    /// This field is optional: this reflects the
    /// fact that some persons might not want to share
    /// their personal info or only some of it.
    pub email: Option<non_empty_string::NonEmptyString>,
}

/// Internal structure to store the data for [Data]
///
/// We have `data1 == data2` if and only if their internal
/// data is the same. This means they would lead to the same
/// file on disk. But the internal id issuer might have a different
/// state.
///
/// [InnerData] represents this actual 'on-disk' data so we can
/// directly use `derive(PartialEq, Eq)` with it. The implementation
/// of [Eq] and [PartialEq] for [Data] relies on it.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct InnerData {
    pub params: colloscope_params::Parameters,
    pub colloscope: colloscopes::Colloscope,
    pub export_config: export_config::ExportConfig,
}

#[derive(Debug, Error, PartialEq, Eq, Clone)]
pub enum InnerDataError {
    #[error("Duplicate ids")]
    DuplicateIds,
    #[error("Error in paramters: {0}")]
    Params(#[from] InvariantError),
    #[error("Error in colloscope: {0}")]
    ColloscopeError(#[from] ColloscopeError),
}

impl InnerData {
    fn ids(&self) -> impl Iterator<Item = u64> {
        self.params.ids()
    }

    fn check_no_duplicate_ids(&self) -> bool {
        let mut ids_so_far = BTreeSet::new();

        for id in self.ids() {
            if !ids_so_far.insert(id) {
                return false;
            }
        }

        true
    }

    pub fn check_invariants(&self) -> Result<(), InnerDataError> {
        if !self.check_no_duplicate_ids() {
            return Err(InnerDataError::DuplicateIds);
        }

        self.params.check_invariants()?;
        self.colloscope.validate_against_params(&self.params)?;

        Ok(())
    }
}

/// Complete data that can be handled in the colloscope
///
/// This [Data] structure contains all the data that can
/// be manipulated in collomatique. It contains the list
/// of students, of teachers, the various interrogations,
/// a description of constraints etc. It also contains the
/// various colloscopes that have been generated or edited.
///
/// It cannot be modified or accessed directly. To the other
/// crates, this is an opaque type.
///
/// It does not necesserally correlate exactly to the data stored
/// on disk. This is to allow versioning.
#[derive(Debug)]
pub struct Data {
    id_issuer: std::sync::Mutex<IdIssuer>,
    inner_data: InnerData,
}

impl Clone for Data {
    fn clone(&self) -> Self {
        let guard = self.id_issuer.lock().unwrap();

        let id_issuer = guard.clone();
        Data {
            id_issuer: std::sync::Mutex::new(id_issuer),
            inner_data: self.inner_data.clone(),
        }
    }
}

impl PartialEq for Data {
    fn eq(&self, other: &Self) -> bool {
        self.inner_data == other.inner_data
    }
}

impl Eq for Data {}

/// Errors for colloscopes modification
///
/// These errors can be returned when trying to modify [Data].
#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum Error {
    #[error(transparent)]
    Student(#[from] StudentError),
    #[error(transparent)]
    Period(#[from] PeriodError),
    #[error(transparent)]
    Week(#[from] WeekError),
    #[error(transparent)]
    Subject(#[from] SubjectError),
    #[error(transparent)]
    Teacher(#[from] TeacherError),
    #[error(transparent)]
    Assignment(#[from] AssignmentError),
    #[error(transparent)]
    WeekPattern(#[from] WeekPatternError),
    #[error(transparent)]
    Slot(#[from] SlotError),
    #[error(transparent)]
    Incompat(#[from] IncompatError),
    #[error(transparent)]
    GroupList(#[from] GroupListError),
    #[error(transparent)]
    Settings(#[from] SettingsError),
    #[error(transparent)]
    Pairing(#[from] PairingError),
    #[error(transparent)]
    SlotPairing(#[from] SlotPairingError),
    #[error(transparent)]
    Balancing(#[from] BalancingError),
    #[error(transparent)]
    Colloscope(#[from] ColloscopeError),
    #[error(transparent)]
    ExportConfig(#[from] ExportConfigError),
    #[error(transparent)]
    GlobalUpdate(#[from] InnerDataError),
}

/// Errors of [Data::force_apply]: only op preconditions (the carve-out subset —
/// no-clobber, op-target existence, positions/anchors, empty-first protocol),
/// never invariants. Invariant breaks are the caller's business via a checker
/// (`InnerData::check_invariants` / `broken_invariants`) plus rollback.
///
/// Mirrors [Error] 1:1 with `#[from]` transparency, minus the `GlobalUpdate`
/// arm: the forced `GlobalUpdate` drops the pre-gate and is infallible. Each
/// arm wraps a per-domain `*PrecheckError` (the carve-out subset of the
/// matching `*Error`); the three value-only domains carry empty enums.
#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum PrecheckError {
    #[error(transparent)]
    Student(#[from] StudentPrecheckError),
    #[error(transparent)]
    Period(#[from] PeriodPrecheckError),
    #[error(transparent)]
    Week(#[from] WeekPrecheckError),
    #[error(transparent)]
    Subject(#[from] SubjectPrecheckError),
    #[error(transparent)]
    Teacher(#[from] TeacherPrecheckError),
    #[error(transparent)]
    Assignment(#[from] AssignmentPrecheckError),
    #[error(transparent)]
    WeekPattern(#[from] WeekPatternPrecheckError),
    #[error(transparent)]
    Slot(#[from] SlotPrecheckError),
    #[error(transparent)]
    Incompat(#[from] IncompatPrecheckError),
    #[error(transparent)]
    GroupList(#[from] GroupListPrecheckError),
    #[error(transparent)]
    Settings(#[from] SettingsPrecheckError),
    #[error(transparent)]
    Pairing(#[from] PairingPrecheckError),
    #[error(transparent)]
    SlotPairing(#[from] SlotPairingPrecheckError),
    #[error(transparent)]
    Balancing(#[from] BalancingPrecheckError),
    #[error(transparent)]
    Colloscope(#[from] ColloscopePrecheckError),
    #[error(transparent)]
    ExportConfig(#[from] ExportConfigPrecheckError),
}

/// Error surface of the apply/check/rollback gate ([Data::try_apply]).
///
/// Three tiers. [ApplyError::Precheck] is bad op input caught before any
/// mutation (the state was never touched). [ApplyError::Logic] and
/// [ApplyError::Invariants] are reported after a forced apply and a rollback,
/// so the state is left bit-identical to before the op.
#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum ApplyError {
    /// Bad op input (no-clobber, dangling target, bad position/anchor).
    /// The state was never touched.
    #[error(transparent)]
    Precheck(#[from] PrecheckError),
    /// The op would land logically impossible rows; rolled back.
    ///
    /// Only reachable from data built outside this crate (`GlobalUpdate`
    /// payloads, decode): ordinary elementary ops cannot construct logically
    /// impossible rows since the value types were sealed.
    #[error("the operation would leave logically impossible data: {}", format_error_set(.0))]
    Logic(BTreeSet<LogicError>),
    /// The op would break fixable invariants; rolled back. At step 6 this is
    /// what the cascade resolves; at step 5 it is simply an error.
    #[error("the operation would break data invariants: {}", format_error_set(.0))]
    Invariants(BTreeSet<FixableInvariant>),
}

/// Itemises a set of errors through each entry's own [std::fmt::Display] so a
/// UI dialog can surface a meaningful message without learning the vocabulary.
fn format_error_set<T: std::fmt::Display>(set: &BTreeSet<T>) -> String {
    set.iter().map(T::to_string).collect::<Vec<_>>().join("; ")
}

/// Error surface of [Data::from_inner_data] — rebuilding a [Data] from a loaded
/// [InnerData]. A loaded file must be fully valid (broken states never exist
/// outside the apply/check/rollback primitive), so any non-clean checker result
/// is an error here.
#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum FromInnerDataError {
    #[error(transparent)]
    IdError(#[from] tools::IdError),
    /// The loaded data would leave logically impossible rows.
    #[error("the loaded data is logically impossible: {}", format_error_set(.0))]
    Logic(BTreeSet<LogicError>),
    /// The loaded data breaks fixable invariants (dangling references or broken
    /// convergence facts).
    #[error("the loaded data breaks invariants: {}", format_error_set(.0))]
    BrokenInvariants(BTreeSet<FixableInvariant>),
}

impl InMemoryData for Data {
    type OriginalOperation = Op;
    type AnnotatedOperation = AnnotatedOp;
    type NewInfo = Option<NewId>;
    type Error = Error;
    type ApplyError = ApplyError;

    fn annotate(&self, op: Op) -> (AnnotatedOp, Option<NewId>) {
        let mut guard = self.id_issuer.lock().unwrap();
        AnnotatedOp::annotate(op, &mut guard)
    }

    fn apply(
        &mut self,
        op: &Self::AnnotatedOperation,
    ) -> std::result::Result<Self::AnnotatedOperation, Self::Error> {
        let backward = match op {
            AnnotatedOp::Student(student_op) => {
                AnnotatedOp::Student(self.apply_student(student_op)?)
            }
            AnnotatedOp::Period(period_op) => AnnotatedOp::Period(self.apply_period(period_op)?),
            AnnotatedOp::Week(week_op) => AnnotatedOp::Week(self.apply_week(week_op)?),
            AnnotatedOp::Subject(subject_op) => {
                AnnotatedOp::Subject(self.apply_subject(subject_op)?)
            }
            AnnotatedOp::Teacher(teacher_op) => {
                AnnotatedOp::Teacher(self.apply_teacher(teacher_op)?)
            }
            AnnotatedOp::Assignment(assignment_op) => {
                AnnotatedOp::Assignment(self.apply_assignment(assignment_op)?)
            }
            AnnotatedOp::WeekPattern(week_pattern_op) => {
                AnnotatedOp::WeekPattern(self.apply_week_pattern(week_pattern_op)?)
            }
            AnnotatedOp::Slot(slot_op) => AnnotatedOp::Slot(self.apply_slot(slot_op)?),
            AnnotatedOp::Incompat(incompat_op) => {
                AnnotatedOp::Incompat(self.apply_incompat(incompat_op)?)
            }
            AnnotatedOp::Pairing(pairing_op) => {
                AnnotatedOp::Pairing(self.apply_pairing(pairing_op)?)
            }
            AnnotatedOp::SlotPairing(slot_pairing_op) => {
                AnnotatedOp::SlotPairing(self.apply_slot_pairing(slot_pairing_op)?)
            }
            AnnotatedOp::GroupList(group_list_op) => {
                AnnotatedOp::GroupList(self.apply_group_list(group_list_op)?)
            }
            AnnotatedOp::Settings(settings_op) => {
                AnnotatedOp::Settings(self.apply_settings(settings_op)?)
            }
            AnnotatedOp::Balancing(balancing_op) => {
                AnnotatedOp::Balancing(self.apply_balancing(balancing_op)?)
            }
            AnnotatedOp::Colloscope(colloscope_op) => {
                AnnotatedOp::Colloscope(self.apply_colloscope(colloscope_op)?)
            }
            AnnotatedOp::ExportConfig(export_config_op) => {
                AnnotatedOp::ExportConfig(self.apply_export_config(export_config_op)?)
            }
            AnnotatedOp::GlobalUpdate(new_inner_data) => {
                new_inner_data.check_invariants()?;
                let old = std::mem::replace(&mut self.inner_data, new_inner_data.clone());
                AnnotatedOp::GlobalUpdate(old)
            }
        };
        self.check_invariants();
        Ok(backward)
    }

    /// The apply/check/rollback gate: snapshot, [Data::force_apply], check with
    /// [InnerData::broken_invariants], and roll back on any breakage.
    ///
    /// On the accepted path the id-issuer high-water assert
    /// ([Data::assert_id_issuer_high_water]) is the surviving [Data]-level
    /// companion of the checker. It cannot fire through the [Manager] surface:
    /// `annotate` draws every fresh id from this issuer, and the `GlobalUpdate`
    /// annotate arm absorbs foreign payload ids up front via
    /// `IdIssuer::skip_to_id`. Its only trigger is an [AnnotatedOp] transplanted
    /// from another [Data] instance through this raw entry point — a caller bug,
    /// hence a panic rather than an error arm.
    fn try_apply(
        &mut self,
        op: &Self::AnnotatedOperation,
    ) -> std::result::Result<Self::AnnotatedOperation, Self::ApplyError> {
        // Snapshot everything an op could conceivably touch. `force_apply` never
        // uses the id issuer today (ids are issued in `annotate`), but the issuer
        // is a single counter — snapshotting it keeps rollback total even if a
        // later change to a `force_apply_*` copy starts touching it. Note what it
        // must *not* undo: `annotate` runs before `try_apply` and its issued ids
        // stay burned on failure, exactly as today — history ids are never reused.
        let snapshot = self.inner_data.clone();
        let issuer_snapshot = self.id_issuer.lock().unwrap().clone();

        // Precheck failures return before any mutation (by construction of the
        // `force_apply_*` copies), so the state is untouched on this arm.
        let backward = self.force_apply(op)?;

        match self.inner_data.broken_invariants() {
            Err(logic) => {
                self.inner_data = snapshot;
                *self.id_issuer.lock().unwrap() = issuer_snapshot;
                Err(ApplyError::Logic(logic))
            }
            Ok(fixable) if !fixable.is_empty() => {
                self.inner_data = snapshot;
                *self.id_issuer.lock().unwrap() = issuer_snapshot;
                Err(ApplyError::Invariants(fixable))
            }
            Ok(_empty) => {
                self.assert_id_issuer_high_water();
                Ok(backward)
            }
        }
    }
}

impl Data {
    /// Applies `op` without checking invariants. Carve-out preconditions still
    /// hold (no-clobber, op-target existence, positions/anchors, empty-first
    /// protocol) and surface as [PrecheckError]; a failed call leaves the state
    /// unchanged. A *successful* call may leave the state invalid: the caller
    /// owns running a checker ([InnerData::check_invariants] /
    /// [InnerData::broken_invariants]) and restoring a snapshot on failure.
    ///
    /// This is an independent thin copy of [InMemoryData::apply] (each arm calls
    /// `force_apply_*`, the carve-out-only twin of `apply_*`). Three differences
    /// from `apply`: errors land in [PrecheckError]; the `GlobalUpdate` arm drops
    /// the `check_invariants()?` pre-gate (this *is* the force door); and the
    /// trailing `check_invariants()` panic net is omitted (the state is allowed
    /// to be invalid here). It is the step-5 apply/check/restore primitive; today
    /// the step-4 differential fuzz exercises it.
    pub fn force_apply(
        &mut self,
        op: &AnnotatedOp,
    ) -> std::result::Result<AnnotatedOp, PrecheckError> {
        let backward = match op {
            AnnotatedOp::Student(o) => AnnotatedOp::Student(self.force_apply_student(o)?),
            AnnotatedOp::Period(o) => AnnotatedOp::Period(self.force_apply_period(o)?),
            AnnotatedOp::Week(o) => AnnotatedOp::Week(self.force_apply_week(o)?),
            AnnotatedOp::Subject(o) => AnnotatedOp::Subject(self.force_apply_subject(o)?),
            AnnotatedOp::Teacher(o) => AnnotatedOp::Teacher(self.force_apply_teacher(o)?),
            AnnotatedOp::Assignment(o) => AnnotatedOp::Assignment(self.force_apply_assignment(o)?),
            AnnotatedOp::WeekPattern(o) => {
                AnnotatedOp::WeekPattern(self.force_apply_week_pattern(o)?)
            }
            AnnotatedOp::Slot(o) => AnnotatedOp::Slot(self.force_apply_slot(o)?),
            AnnotatedOp::Incompat(o) => AnnotatedOp::Incompat(self.force_apply_incompat(o)?),
            AnnotatedOp::Pairing(o) => AnnotatedOp::Pairing(self.force_apply_pairing(o)?),
            AnnotatedOp::SlotPairing(o) => {
                AnnotatedOp::SlotPairing(self.force_apply_slot_pairing(o)?)
            }
            AnnotatedOp::GroupList(o) => AnnotatedOp::GroupList(self.force_apply_group_list(o)?),
            AnnotatedOp::Settings(o) => AnnotatedOp::Settings(self.force_apply_settings(o)?),
            AnnotatedOp::Balancing(o) => AnnotatedOp::Balancing(self.force_apply_balancing(o)?),
            AnnotatedOp::Colloscope(o) => AnnotatedOp::Colloscope(self.force_apply_colloscope(o)?),
            AnnotatedOp::ExportConfig(o) => {
                AnnotatedOp::ExportConfig(self.force_apply_export_config(o)?)
            }
            AnnotatedOp::GlobalUpdate(new_inner_data) => {
                // no check_invariants pre-gate: this is the force door
                let old = std::mem::replace(&mut self.inner_data, new_inner_data.clone());
                AnnotatedOp::GlobalUpdate(old)
            }
        };
        // no panic net: the state is allowed to be invalid here
        Ok(backward)
    }
}

impl Data {
    /// USED INTERNALLY
    ///
    /// Asserts the id-issuer high-water invariant: the issuer's internal counter
    /// is strictly greater than every id currently live in the data, so a freshly
    /// issued id can never collide with an existing one.
    ///
    /// This is [Data]-level state (the issuer is deliberately not part of
    /// [InnerData]), so it cannot live in [InnerData::check_invariants] or
    /// [InnerData::broken_invariants]; it is the surviving companion the
    /// apply/check/rollback gate ([Data::try_apply]) runs on the accepted path.
    fn assert_id_issuer_high_water(&self) {
        let max_id = self.inner_data.ids().max();

        if let Some(id) = max_id {
            let guard = self.id_issuer.lock().expect("No error on lock");
            if id >= guard.get_internal_counter() {
                panic!("IdIssuer internal counter is not greater than all internal ids");
            }
        }
    }

    /// USED INTERNALLY
    ///
    /// Checks all the invariants of data (the old-checker panic net, kept for the
    /// checked [InMemoryData::apply] path during the step-5 migration window).
    fn check_invariants(&self) {
        self.assert_id_issuer_high_water();

        self.inner_data
            .check_invariants()
            .expect("Invariants should be valid in Data");
    }
}

impl Default for Data {
    fn default() -> Self {
        Self::new()
    }
}

impl Data {
    /// Create a new [Data]
    ///
    /// This [Data] is basically empty and corresponds to the
    /// state of a new file
    pub fn new() -> Data {
        Self::from_inner_data(InnerData::default()).expect("Default data should be valid")
    }

    /// Create a new [Data] from existing data
    ///
    /// This will check the consistency of the data
    /// and will also do some internal checks, so this might fail.
    pub fn from_inner_data(inner_data: InnerData) -> Result<Data, FromInnerDataError> {
        // A loaded file must be fully valid: hard error on a logic breakage and
        // on any non-empty fixable set. Broken states never exist outside the
        // apply/check/rollback primitive.
        match inner_data.broken_invariants() {
            Err(logic) => return Err(FromInnerDataError::Logic(logic)),
            Ok(set) if !set.is_empty() => return Err(FromInnerDataError::BrokenInvariants(set)),
            Ok(_) => {}
        }

        let id_issuer = IdIssuer::new(inner_data.ids())?;

        let data = Data {
            id_issuer: std::sync::Mutex::new(id_issuer),
            inner_data,
        };

        // Data-level companion of the checker (the id issuer is not part of
        // InnerData, so broken_invariants cannot see it).
        data.assert_id_issuer_high_water();

        Ok(data)
    }

    /// Returns a non-mutable reference to internal data
    ///
    /// Elementary ops allow the edition of data. But between two ops
    /// you can inspect the current data via this function
    pub fn get_inner_data(&self) -> &InnerData {
        &self.inner_data
    }

    /// Similar to [Self::get_inner_data] but consumes the [Data] and returns
    /// an owned [InnerData]
    pub fn into_inner_data(self) -> InnerData {
        self.inner_data
    }
}

#[cfg(test)]
mod force_apply_tests {
    //! Step-4 commit 2.2 pins for [Data::force_apply]: carve-out guards still
    //! fire (leaving the state unchanged), stripped invariant guards let a
    //! forced op land an *invalid* state that both checkers agree on, and a
    //! forced *valid* op is byte-identical to the checked `apply` (the standing
    //! anti-drift pin on the thin copies). The step-4 fuzz generalises these.

    use crate::ids::{Id, PeriodId, StudentId, SubjectId, WeekPatternId};
    use crate::invariants::assert_differential;
    use crate::ops::{
        AnnotatedOp, AnnotatedPeriodOp, AnnotatedStudentOp, AnnotatedSubjectOp, AssignmentOp, Op,
        PeriodOp, StudentOp, SubjectOp, WeekOp,
    };
    use crate::students::Student;
    use crate::subjects::Subject;
    use crate::week_patterns::WeekPattern;
    use crate::weeks::WeekDesc;
    use crate::{Data, FixableInvariant, InnerData, PrecheckError, StudentPrecheckError};
    use collomatique_state::InMemoryData;
    use std::collections::BTreeSet;

    /// Applies a (valid) op through the checked path and returns its annotated
    /// form, so callers can read back the freshly issued ids.
    fn apply(data: &mut Data, op: Op) -> AnnotatedOp {
        let (annotated, _) = data.annotate(op);
        data.apply(&annotated).expect("valid op should apply");
        annotated
    }

    /// The smallest state where a student is referenced by an assignments row:
    /// one period, one subject running on it, one student assigned. Returns
    /// `(data, period, subject, student)`.
    fn data_with_assignment() -> (Data, PeriodId, SubjectId, StudentId) {
        let mut data = Data::default();
        let period = match apply(&mut data, Op::Period(PeriodOp::AddFront)) {
            AnnotatedOp::Period(AnnotatedPeriodOp::AddFront(p)) => p,
            other => panic!("unexpected annotated op {other:?}"),
        };
        let subject = match apply(
            &mut data,
            Op::Subject(SubjectOp::AddAfter(None, Subject::default())),
        ) {
            AnnotatedOp::Subject(AnnotatedSubjectOp::AddAfter(s, _, _)) => s,
            other => panic!("unexpected annotated op {other:?}"),
        };
        let student = match apply(&mut data, Op::Student(StudentOp::Add(Student::default()))) {
            AnnotatedOp::Student(AnnotatedStudentOp::Add(u, _)) => u,
            other => panic!("unexpected annotated op {other:?}"),
        };
        apply(
            &mut data,
            Op::Assignment(AssignmentOp::Assign(period, student, subject, true)),
        );
        (data, period, subject, student)
    }

    #[test]
    fn force_remove_referenced_student_lands_a_dangling_fk() {
        let (mut data, _period, _subject, student) = data_with_assignment();
        assert!(
            data.get_inner_data().check_invariants().is_ok(),
            "the built state is valid"
        );

        // The Remove scans (colloscope / group-list / assignments / settings)
        // are stripped, so the forced removal succeeds even though the student
        // is still referenced by an assignments row.
        let (remove, _) = data.annotate(Op::Student(StudentOp::Remove(student)));
        data.force_apply(&remove)
            .expect("forced remove of a live student succeeds (scans stripped)");

        // Both checkers must see the now-dangling reference, and the three-part
        // differential must agree on it.
        assert_differential(data.get_inner_data());
        let broken = data.get_inner_data().broken_invariants();
        assert!(
            matches!(&broken, Ok(set) if set.iter().any(|f| matches!(f, FixableInvariant::DanglingFk(_)))),
            "expected a dangling-FK report, got {broken:?}"
        );
        assert!(
            data.get_inner_data().check_invariants().is_err(),
            "the old checker must also reject the dangling state"
        );
    }

    #[test]
    fn force_add_on_existing_id_hard_errors_and_leaves_state_unchanged() {
        let (mut data, _period, _subject, student) = data_with_assignment();
        let before = data.clone();

        // A directly-built Add re-using a live id — the no-clobber carve-out is
        // kept, so this hard-errors without mutating.
        let dup = AnnotatedOp::Student(AnnotatedStudentOp::Add(student, Student::default()));
        let err = data.force_apply(&dup).unwrap_err();
        assert!(
            matches!(err, PrecheckError::Student(StudentPrecheckError::StudentIdAlreadyExists(id)) if id == student),
            "expected StudentIdAlreadyExists, got {err:?}"
        );
        assert!(
            data == before,
            "a failed force_apply must not mutate the state"
        );
    }

    #[test]
    fn force_update_on_dangling_target_hard_errors_and_leaves_state_unchanged() {
        let (mut data, _period, _subject, _student) = data_with_assignment();
        let before = data.clone();

        // Op-target existence is kept, so an Update on an absent id hard-errors.
        let ghost = unsafe { StudentId::new(9_999) };
        let update = AnnotatedOp::Student(AnnotatedStudentOp::Update(ghost, Student::default()));
        let err = data.force_apply(&update).unwrap_err();
        assert!(
            matches!(err, PrecheckError::Student(StudentPrecheckError::InvalidStudentId(id)) if id == ghost),
            "expected InvalidStudentId, got {err:?}"
        );
        assert!(
            data == before,
            "a failed force_apply must not mutate the state"
        );
    }

    #[test]
    fn force_global_update_drops_the_pre_gate_and_lands_an_invalid_state() {
        // A valid vehicle; its inner is replaced wholesale.
        let mut data = Data::default();

        // A corrupt inner: a student and a week pattern sharing the same raw id
        // — a duplicated-id LogicError that `apply`'s GlobalUpdate pre-gate would
        // reject. `force_apply` drops that gate, so the corrupt state lands.
        let mut corrupt = InnerData::default();
        let student = unsafe { StudentId::new(1) };
        let pattern = unsafe { WeekPatternId::new(1) };
        corrupt
            .params
            .students
            .student_map
            .insert(student, Student::default());
        corrupt.params.week_patterns.week_pattern_map.insert(
            pattern,
            WeekPattern {
                name: "P".into(),
                excluded_weeks: BTreeSet::new(),
            },
        );

        let op = AnnotatedOp::GlobalUpdate(corrupt);
        data.force_apply(&op)
            .expect("forced GlobalUpdate is infallible (no pre-gate)");

        assert!(
            data.get_inner_data().check_invariants().is_err(),
            "the duplicated-id state is invalid"
        );
        assert_differential(data.get_inner_data());
    }

    #[test]
    fn forced_valid_student_add_equals_checked_apply() {
        let data = Data::default();
        let (add, _) = data.annotate(Op::Student(StudentOp::Add(Student::default())));

        let mut checked = data.clone();
        let mut forced = data.clone();
        let checked_rev = checked.apply(&add).expect("valid op");
        let forced_rev = forced.force_apply(&add).expect("valid op");

        assert_eq!(checked.get_inner_data(), forced.get_inner_data());
        assert_eq!(checked_rev, forced_rev);
    }

    #[test]
    fn forced_valid_week_add_equals_checked_apply() {
        // Weeks exercise the copied helpers (`force_add_week` &c.), the highest
        // drift-risk spot (F2). Build a period, then compare the two paths on a
        // week AddFront.
        let mut data = Data::default();
        let period = match apply(&mut data, Op::Period(PeriodOp::AddFront)) {
            AnnotatedOp::Period(AnnotatedPeriodOp::AddFront(p)) => p,
            other => panic!("unexpected annotated op {other:?}"),
        };

        let (add_week, _) = data.annotate(Op::Week(WeekOp::AddFront(period, WeekDesc::default())));
        let mut checked = data.clone();
        let mut forced = data.clone();
        let checked_rev = checked.apply(&add_week).expect("valid op");
        let forced_rev = forced.force_apply(&add_week).expect("valid op");

        assert_eq!(checked.get_inner_data(), forced.get_inner_data());
        assert_eq!(checked_rev, forced_rev);
    }
}

#[cfg(test)]
mod try_apply_tests {
    //! Step-5 commit 1 pins for [Data::try_apply]: the apply/check/rollback gate
    //! rolls a broken landing back to a bit-identical pre-op state and reports it
    //! precisely; a `GlobalUpdate` carrying logically impossible (duplicated-id)
    //! data comes back as [ApplyError::Logic], rolled back.

    use crate::ids::{Id, StudentId, WeekPatternId};
    use crate::ops::{
        AnnotatedOp, AnnotatedPeriodOp, AnnotatedStudentOp, AnnotatedSubjectOp, AssignmentOp, Op,
        PeriodOp, StudentOp, SubjectOp,
    };
    use crate::students::Student;
    use crate::subjects::Subject;
    use crate::week_patterns::WeekPattern;
    use crate::{ApplyError, Data, FixableInvariant, InnerData};
    use collomatique_state::InMemoryData;
    use std::collections::BTreeSet;

    /// Applies a (valid) op through the checked path and returns its annotated
    /// form, so callers can read back the freshly issued ids.
    fn apply(data: &mut Data, op: Op) -> AnnotatedOp {
        let (annotated, _) = data.annotate(op);
        data.apply(&annotated).expect("valid op should apply");
        annotated
    }

    /// The smallest state where a student is referenced by an assignments row:
    /// one period, one subject running on it, one student assigned.
    fn data_with_assignment() -> (Data, StudentId) {
        let mut data = Data::default();
        let period = match apply(&mut data, Op::Period(PeriodOp::AddFront)) {
            AnnotatedOp::Period(AnnotatedPeriodOp::AddFront(p)) => p,
            other => panic!("unexpected annotated op {other:?}"),
        };
        let subject = match apply(
            &mut data,
            Op::Subject(SubjectOp::AddAfter(None, Subject::default())),
        ) {
            AnnotatedOp::Subject(AnnotatedSubjectOp::AddAfter(s, _, _)) => s,
            other => panic!("unexpected annotated op {other:?}"),
        };
        let student = match apply(&mut data, Op::Student(StudentOp::Add(Student::default()))) {
            AnnotatedOp::Student(AnnotatedStudentOp::Add(u, _)) => u,
            other => panic!("unexpected annotated op {other:?}"),
        };
        apply(
            &mut data,
            Op::Assignment(AssignmentOp::Assign(period, student, subject, true)),
        );
        (data, student)
    }

    #[test]
    fn try_apply_invariant_breaking_op_rolls_back_and_reports() {
        let (mut data, student) = data_with_assignment();
        let before = data.clone();

        // Removing a still-referenced student lands a dangling assignments FK
        // (the Remove scans are stripped in `force_apply`); the gate must roll the
        // state back and report it as an Invariants error.
        let (remove, _) = data.annotate(Op::Student(StudentOp::Remove(student)));
        let err = data.try_apply(&remove).unwrap_err();

        match err {
            ApplyError::Invariants(set) => assert!(
                set.iter()
                    .any(|f| matches!(f, FixableInvariant::DanglingFk(_))),
                "expected a dangling-FK report, got {set:?}"
            ),
            other => panic!("expected Invariants, got {other:?}"),
        }
        assert!(
            data == before,
            "a rolled-back try_apply must leave the state bit-identical"
        );
    }

    #[test]
    fn try_apply_global_update_with_duplicated_id_errors_logic_and_rolls_back() {
        let mut data = Data::default();
        let before = data.clone();

        // A corrupt inner: a student and a week pattern sharing raw id 1 — a
        // duplicated-id LogicError. Through the gate this rolls back and surfaces
        // as ApplyError::Logic (post-sealing the only route into that arm).
        let mut corrupt = InnerData::default();
        let student = unsafe { StudentId::new(1) };
        let pattern = unsafe { WeekPatternId::new(1) };
        corrupt
            .params
            .students
            .student_map
            .insert(student, Student::default());
        corrupt.params.week_patterns.week_pattern_map.insert(
            pattern,
            WeekPattern {
                name: "P".into(),
                excluded_weeks: BTreeSet::new(),
            },
        );

        let op = AnnotatedOp::GlobalUpdate(corrupt);
        let err = data.try_apply(&op).unwrap_err();

        assert!(
            matches!(err, ApplyError::Logic(ref set) if !set.is_empty()),
            "expected a non-empty Logic error, got {err:?}"
        );
        assert!(
            data == before,
            "a rolled-back GlobalUpdate must leave the state bit-identical"
        );
    }
}
