//! Colloscopes state crate
//!
//! This crate implements the various concepts of [collomatique-state]
//! and the various traits for the specific case of colloscope representation.
//!

use serde::{Deserialize, Serialize};
use thiserror::Error;

use collomatique_state::partial_order::option_lift_discrete;
use collomatique_state::{ContentOrd, InMemoryData, Operation, tools};
use std::collections::BTreeSet;

/// Internal re-export of the generic table containers.
///
/// Tables are an implementation detail of this crate: consumers read them
/// through the inherent read API (`get`/`contains`/`iter`/`keys`/`values`/
/// `get_at`/…) and build their own copy with an explicit
/// `.iter().map(…).collect()` into a plain `BTreeMap`/`Vec` when they need one.
/// Kept `pub(crate)` so the path does not leak.
pub(crate) use collomatique_state::{OrderedTable, Table};

pub mod ids;
use ids::Id;
use ids::IdIssuer;
pub use ids::{
    GroupListId, IncompatId, NewId, PairingRuleId, PeriodId, SlotId, SlotPairingRuleId, StudentId,
    SubjectId, TeacherId, WeekId, WeekPatternId,
};
pub mod ops;
pub use ops::{
    AnnotatedOp, AssignmentOp, BalancingOp, ColloscopeOp, ExportConfigOp, GroupListOp, IncompatOp,
    Op, PairingOp, PeriodOp, SettingsOp, SlotOp, SlotPairingOp, StudentOp, SubjectOp, TeacherOp,
    WeekOp, WeekPatternOp,
};
pub use subjects::{
    Subject, SubjectInterrogationParameters, SubjectParameters, SubjectPeriodicity,
};

pub mod assignments;
pub mod balancing;
pub mod colloscope_params;
pub mod colloscopes;
pub mod compact;
pub mod export_config;
pub mod group_lists;
pub mod incompats;
pub mod invariants;
pub mod non_empty_range;
pub mod pairings;
// Semantic pins for the document order (step 6.5). In-crate, because several
// of the values they compare live behind private fields.
#[cfg(test)]
mod partial_order_tests;
pub mod periods;
pub mod refs;
// The cascade's resolution map. Private: the arms stay in, and the module
// surfaces through the `collomatique_state::Fixable` impl it holds for [Data]
// and through the [Fix] vocabulary that impl answers with.
mod resolution;
pub mod settings;
pub mod slot_pairings;
pub mod slots;
pub mod soft_param;
pub mod students;
pub mod subjects;
pub mod teachers;
pub mod week_patterns;
pub mod weeks;

pub use invariants::{Convergence, FixableInvariant, LogicError};
pub use non_empty_range::{EmptyRangeError, NonEmptyRangeInclusive};
// The cascade's repair vocabulary: what the resolution map answers, and the
// only part of a cascade's reasoning that reaches a consumer.
pub use resolution::Fix;

// Per-domain precheck error enums for [Data::force_apply] — the carve-out
// subset of each domain's error surface (step-3 survey Table 2). Introduced in
// step 4; this is the error vocabulary that survives step 5.
pub use assignments::AssignmentPrecheckError;
pub use balancing::BalancingPrecheckError;
pub use colloscopes::ColloscopePrecheckError;
pub use export_config::ExportConfigPrecheckError;
pub use group_lists::GroupListPrecheckError;
pub use incompats::IncompatPrecheckError;
pub use pairings::PairingPrecheckError;
pub use periods::PeriodPrecheckError;
pub use settings::SettingsPrecheckError;
pub use slot_pairings::SlotPairingPrecheckError;
pub use slots::SlotPrecheckError;
pub use students::StudentPrecheckError;
pub use subjects::SubjectPrecheckError;
pub use teachers::TeacherPrecheckError;
pub use week_patterns::WeekPatternPrecheckError;
pub use weeks::WeekPrecheckError;

pub use refs::{
    GroupListRefSite, PeriodRefSite, RefVisitor, Reference, SlotRefSite, StudentRefSite,
    SubjectRefSite, TeacherRefSite, WeekPatternRefSite, WeekRefSite,
};

// Joined views generated by `#[derive(Join)]` on the entity structs — the
// reference-based read shape (every FK resolved to a borrow of its entity).
pub use incompats::JoinedIncompatibility;
pub use pairings::{JoinedPairingRule, JoinedRulePart};
pub use slot_pairings::{JoinedSlotPairingRule, JoinedSlotRulePart};
pub use slots::JoinedSlot;
pub use students::JoinedStudent;
pub use subjects::JoinedSubject;
pub use teachers::JoinedTeacher;

/// Description of a person with contacts
///
/// This type is used to describe both students and teachers.
/// Each student and teacher has its own card with name and contacts.
/// There are not used for the colloscope solving process
/// but can help produce a nice colloscope output with contact info.
#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize, ContentOrd)]
pub struct PersonWithContact {
    /// Surname of the person
    ///
    /// Though this field can be an empty string,
    /// it is considered mandatory internally
    pub surname: String,

    /// Firstname of the person
    ///
    /// Though this field can be an empty string,
    /// it is considered mandatory internally
    pub firstname: String,

    /// Person's telephone number
    ///
    /// This field is optional: this reflects the
    /// fact that some persons might not want to share
    /// their personal info or only some of it.
    // `NonEmptyString` is foreign, so the helper supplies the `Option` rule:
    // clearing a contact is removing content, two different numbers are
    // incomparable.
    #[ord(with = option_lift_discrete)]
    pub tel: Option<non_empty_string::NonEmptyString>,

    /// Person's email
    ///
    /// This field is optional: this reflects the
    /// fact that some persons might not want to share
    /// their personal info or only some of it.
    #[ord(with = option_lift_discrete)]
    pub email: Option<non_empty_string::NonEmptyString>,
}

/// Internal structure to store the data for [Data]
///
/// We have `data1 == data2` if and only if their internal
/// data is the same. This means they would lead to the same
/// file on disk. But the internal id issuer might have a different
/// state.
///
/// [InnerData] represents this actual 'on-disk' data so we can
/// directly use `derive(PartialEq, Eq)` with it. The implementation
/// of [Eq] and [PartialEq] for [Data] relies on it.
#[derive(Debug, Clone, PartialEq, Eq, Default, ContentOrd)]
pub struct InnerData {
    pub params: colloscope_params::Parameters,
    pub colloscope: colloscopes::Colloscope,
    pub export_config: export_config::ExportConfig,
}

impl InnerData {
    fn ids(&self) -> impl Iterator<Item = u64> {
        self.params.ids()
    }
}

/// Complete data that can be handled in the colloscope
///
/// This [Data] structure contains all the data that can
/// be manipulated in collomatique. It contains the list
/// of students, of teachers, the various interrogations,
/// a description of constraints etc. It also contains the
/// various colloscopes that have been generated or edited.
///
/// It cannot be modified or accessed directly. To the other
/// crates, this is an opaque type.
///
/// It does not necesserally correlate exactly to the data stored
/// on disk. This is to allow versioning.
#[derive(Clone, Debug, ContentOrd)]
pub struct Data {
    // The document order does not see the issuer: two `Data` with equal
    // inner data are content-equivalent even when their issuers differ —
    // the same quotient the hand-written `PartialEq` below takes.
    #[ord(ignore)]
    id_issuer: IdIssuer,
    inner_data: InnerData,
}

impl PartialEq for Data {
    fn eq(&self, other: &Self) -> bool {
        self.inner_data == other.inner_data
    }
}

impl Eq for Data {}

/// Errors of [Data::force_apply]: only op preconditions (the carve-out subset —
/// no-clobber, op-target existence, positions/anchors), never invariants.
/// Invariant breaks are the caller's business via
/// [InnerData::broken_invariants] plus rollback.
///
/// The forced `GlobalUpdate` drops the pre-gate and is infallible, so this enum
/// has no `GlobalUpdate` arm. Each arm wraps a per-domain `*PrecheckError` (the
/// carve-out subset of op preconditions); the three value-only domains carry
/// empty enums.
#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum PrecheckError {
    #[error(transparent)]
    Student(#[from] StudentPrecheckError),
    #[error(transparent)]
    Period(#[from] PeriodPrecheckError),
    #[error(transparent)]
    Week(#[from] WeekPrecheckError),
    #[error(transparent)]
    Subject(#[from] SubjectPrecheckError),
    #[error(transparent)]
    Teacher(#[from] TeacherPrecheckError),
    #[error(transparent)]
    Assignment(#[from] AssignmentPrecheckError),
    #[error(transparent)]
    WeekPattern(#[from] WeekPatternPrecheckError),
    #[error(transparent)]
    Slot(#[from] SlotPrecheckError),
    #[error(transparent)]
    Incompat(#[from] IncompatPrecheckError),
    #[error(transparent)]
    GroupList(#[from] GroupListPrecheckError),
    #[error(transparent)]
    Settings(#[from] SettingsPrecheckError),
    #[error(transparent)]
    Pairing(#[from] PairingPrecheckError),
    #[error(transparent)]
    SlotPairing(#[from] SlotPairingPrecheckError),
    #[error(transparent)]
    Balancing(#[from] BalancingPrecheckError),
    #[error(transparent)]
    Colloscope(#[from] ColloscopePrecheckError),
    #[error(transparent)]
    ExportConfig(#[from] ExportConfigPrecheckError),
}

/// The unresolvable tier of the gate's error surface: bad op input. Both the
/// carve-out prechecks (design doc §4) and the logic tier live here — an op
/// whose payload would land logically impossible rows is an invalid op.
///
/// [InvalidOp::Logic] stays reachable only from data built outside this crate
/// (`GlobalUpdate` payloads, decode): ordinary elementary ops cannot construct
/// logically impossible rows since the value types were sealed.
#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum InvalidOp {
    /// Bad op input (no-clobber, dangling target, bad position/anchor).
    /// The state was never touched.
    #[error(transparent)]
    Precheck(#[from] PrecheckError),
    /// The op would land logically impossible rows; rolled back.
    #[error("the operation would leave logically impossible data: {}", format_error_set(.0))]
    Logic(BTreeSet<LogicError>),
}

/// Error surface of the apply/check/rollback gate ([Data::apply]): the shared
/// two-tier [collomatique_state::ApplyError] instantiated with this crate's
/// vocabulary. [collomatique_state::ApplyError::InvalidOp] is bad op input
/// (never resolvable); [collomatique_state::ApplyError::BrokenInvariants] is
/// what the cascade resolves (at step 5 it is simply an error).
pub type Error = collomatique_state::ApplyError<InvalidOp, FixableInvariant>;

/// Lets the gate keep writing `self.force_apply(op)?`.
impl From<PrecheckError> for Error {
    fn from(e: PrecheckError) -> Self {
        collomatique_state::ApplyError::InvalidOp(InvalidOp::Precheck(e))
    }
}

/// Itemises a set of errors through each entry's own [std::fmt::Display] so a
/// UI dialog can surface a meaningful message without learning the vocabulary.
fn format_error_set<T: std::fmt::Display>(set: &BTreeSet<T>) -> String {
    set.iter().map(T::to_string).collect::<Vec<_>>().join("; ")
}

/// Error surface of [Data::from_inner_data] — rebuilding a [Data] from a loaded
/// [InnerData]. A loaded file must be fully valid (broken states never exist
/// outside the apply/check/rollback primitive), so any non-clean checker result
/// is an error here.
#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum FromInnerDataError {
    #[error(transparent)]
    IdError(#[from] tools::IdError),
    /// The loaded data would leave logically impossible rows.
    #[error("the loaded data is logically impossible: {}", format_error_set(.0))]
    Logic(BTreeSet<LogicError>),
    /// The loaded data breaks fixable invariants (dangling references or broken
    /// convergence facts).
    #[error("the loaded data breaks invariants: {}", format_error_set(.0))]
    BrokenInvariants(BTreeSet<FixableInvariant>),
}

impl InMemoryData for Data {
    type OriginalOperation = Op;
    type AnnotatedOperation = AnnotatedOp;
    type NewInfo = Option<NewId>;
    type InvalidOp = InvalidOp;
    type Invariant = FixableInvariant;

    fn annotate(&mut self, op: Op) -> (AnnotatedOp, Option<NewId>) {
        AnnotatedOp::annotate(op, &mut self.id_issuer)
    }

    /// The apply/check/rollback gate: snapshot, [Data::force_apply], check with
    /// [InnerData::broken_invariants], and roll back on any breakage.
    ///
    /// On the accepted path the id-issuer high-water assert
    /// (`Data::assert_id_issuer_high_water`) is the surviving [Data]-level
    /// companion of the checker. It cannot fire through the [Manager] surface:
    /// `annotate` draws every fresh id from this issuer, and the `GlobalUpdate`
    /// annotate arm absorbs foreign payload ids up front via
    /// `IdIssuer::skip_to_id`. Its only trigger is an [AnnotatedOp] transplanted
    /// from another [Data] instance through this raw entry point — a caller bug,
    /// hence a panic rather than an error arm.
    fn apply(
        &mut self,
        op: &Self::AnnotatedOperation,
    ) -> std::result::Result<
        Self::AnnotatedOperation,
        collomatique_state::ApplyError<Self::InvalidOp, Self::Invariant>,
    > {
        // Snapshot everything an op could conceivably touch. `force_apply` never
        // uses the id issuer today (ids are issued in `annotate`), but the issuer
        // is a single counter — snapshotting it keeps rollback total even if a
        // later change to a `force_apply_*` copy starts touching it. Note what it
        // must *not* undo: `annotate` runs before `apply` and its issued ids
        // stay burned on failure, exactly as today — history ids are never reused.
        let snapshot = self.inner_data.clone();
        let issuer_snapshot = self.id_issuer.clone();

        // Precheck failures return before any mutation (by construction of the
        // `force_apply_*` copies); the restore below makes that a mechanism
        // rather than a 16-file discipline — a copy that ever mutated before
        // erroring would still leave the state bit-identical. The snapshot is
        // already in hand for the checker arms, so this costs nothing on the
        // accepted path. `e.into()` is the same conversion the `?` used to
        // apply (`From<PrecheckError> for Error`), so the error value is
        // unchanged.
        let backward = match self.force_apply(op) {
            Ok(backward) => backward,
            Err(e) => {
                self.inner_data = snapshot;
                self.id_issuer = issuer_snapshot;
                return Err(e.into());
            }
        };

        match self.inner_data.broken_invariants() {
            Err(logic) => {
                self.inner_data = snapshot;
                self.id_issuer = issuer_snapshot;
                Err(collomatique_state::ApplyError::InvalidOp(InvalidOp::Logic(
                    logic,
                )))
            }
            Ok(fixable) if !fixable.is_empty() => {
                self.inner_data = snapshot;
                self.id_issuer = issuer_snapshot;
                Err(collomatique_state::ApplyError::BrokenInvariants(fixable))
            }
            Ok(_empty) => {
                self.assert_id_issuer_high_water();
                Ok(backward)
            }
        }
    }
}

impl Data {
    /// Applies `op` without checking invariants. Carve-out preconditions still
    /// hold (no-clobber, op-target existence, positions/anchors) and surface
    /// as [PrecheckError]; a failed call leaves the state
    /// unchanged. A *successful* call may leave the state invalid: the caller
    /// owns running the checker ([InnerData::broken_invariants]) and restoring a
    /// snapshot on failure.
    ///
    /// Each arm calls the corresponding `force_apply_*` (the carve-out-only
    /// domain writer). The `GlobalUpdate` arm has no invariant pre-gate — this
    /// *is* the force door — and there is no trailing panic net, since the state
    /// is allowed to be invalid here. It is the force half of the
    /// apply/check/rollback gate ([Data::apply]).
    pub fn force_apply(
        &mut self,
        op: &AnnotatedOp,
    ) -> std::result::Result<AnnotatedOp, PrecheckError> {
        let backward = match op {
            AnnotatedOp::Student(o) => AnnotatedOp::Student(self.force_apply_student(o)?),
            AnnotatedOp::Period(o) => AnnotatedOp::Period(self.force_apply_period(o)?),
            AnnotatedOp::Week(o) => AnnotatedOp::Week(self.force_apply_week(o)?),
            AnnotatedOp::Subject(o) => AnnotatedOp::Subject(self.force_apply_subject(o)?),
            AnnotatedOp::Teacher(o) => AnnotatedOp::Teacher(self.force_apply_teacher(o)?),
            AnnotatedOp::Assignment(o) => AnnotatedOp::Assignment(self.force_apply_assignment(o)?),
            AnnotatedOp::WeekPattern(o) => {
                AnnotatedOp::WeekPattern(self.force_apply_week_pattern(o)?)
            }
            AnnotatedOp::Slot(o) => AnnotatedOp::Slot(self.force_apply_slot(o)?),
            AnnotatedOp::Incompat(o) => AnnotatedOp::Incompat(self.force_apply_incompat(o)?),
            AnnotatedOp::Pairing(o) => AnnotatedOp::Pairing(self.force_apply_pairing(o)?),
            AnnotatedOp::SlotPairing(o) => {
                AnnotatedOp::SlotPairing(self.force_apply_slot_pairing(o)?)
            }
            AnnotatedOp::GroupList(o) => AnnotatedOp::GroupList(self.force_apply_group_list(o)?),
            AnnotatedOp::Settings(o) => AnnotatedOp::Settings(self.force_apply_settings(o)?),
            AnnotatedOp::Balancing(o) => AnnotatedOp::Balancing(self.force_apply_balancing(o)?),
            AnnotatedOp::Colloscope(o) => AnnotatedOp::Colloscope(self.force_apply_colloscope(o)?),
            AnnotatedOp::ExportConfig(o) => {
                AnnotatedOp::ExportConfig(self.force_apply_export_config(o)?)
            }
            AnnotatedOp::GlobalUpdate(new_inner_data) => {
                // no invariant pre-gate: this is the force door
                let old = std::mem::replace(&mut self.inner_data, new_inner_data.clone());
                AnnotatedOp::GlobalUpdate(old)
            }
        };
        // no panic net: the state is allowed to be invalid here
        Ok(backward)
    }
}

impl Data {
    /// USED INTERNALLY
    ///
    /// Asserts the id-issuer high-water invariant: the issuer's internal counter
    /// is strictly greater than every id currently live in the data, so a freshly
    /// issued id can never collide with an existing one.
    ///
    /// This is [Data]-level state (the issuer is deliberately not part of
    /// [InnerData]), so it cannot live in [InnerData::broken_invariants]; it is
    /// the surviving companion the apply/check/rollback gate ([Data::apply])
    /// runs on the accepted path.
    fn assert_id_issuer_high_water(&self) {
        let max_id = self.inner_data.ids().max();

        if let Some(id) = max_id {
            if id >= self.id_issuer.get_internal_counter() {
                panic!("IdIssuer internal counter is not greater than all internal ids");
            }
        }
    }
}

impl Default for Data {
    fn default() -> Self {
        Self::new()
    }
}

impl Data {
    /// Create a new [Data]
    ///
    /// This [Data] is basically empty and corresponds to the
    /// state of a new file
    pub fn new() -> Data {
        Self::from_inner_data(InnerData::default()).expect("Default data should be valid")
    }

    /// Create a new [Data] from existing data
    ///
    /// This will check the consistency of the data
    /// and will also do some internal checks, so this might fail.
    pub fn from_inner_data(inner_data: InnerData) -> Result<Data, FromInnerDataError> {
        // A loaded file must be fully valid: hard error on a logic breakage and
        // on any non-empty fixable set. Broken states never exist outside the
        // apply/check/rollback primitive.
        match inner_data.broken_invariants() {
            Err(logic) => return Err(FromInnerDataError::Logic(logic)),
            Ok(set) if !set.is_empty() => return Err(FromInnerDataError::BrokenInvariants(set)),
            Ok(_) => {}
        }

        let id_issuer = IdIssuer::new(inner_data.ids())?;

        let data = Data {
            id_issuer,
            inner_data,
        };

        // Data-level companion of the checker (the id issuer is not part of
        // InnerData, so broken_invariants cannot see it).
        data.assert_id_issuer_high_water();

        Ok(data)
    }

    /// Returns a non-mutable reference to internal data
    ///
    /// Elementary ops allow the edition of data. But between two ops
    /// you can inspect the current data via this function
    pub fn get_inner_data(&self) -> &InnerData {
        &self.inner_data
    }

    /// Similar to [Self::get_inner_data] but consumes the [Data] and returns
    /// an owned [InnerData]
    pub fn into_inner_data(self) -> InnerData {
        self.inner_data
    }
}

#[cfg(test)]
mod force_apply_tests {
    //! Step-4 commit 2.2 pins for [Data::force_apply], retargeted at step-5
    //! R1.5: carve-out guards still fire (leaving the state unchanged),
    //! stripped invariant guards let a forced op land an *invalid* state that
    //! [InnerData::broken_invariants] reports, and a forced *valid* op is
    //! byte-identical to the gated [Data::apply] (the standing anti-drift
    //! pin on the thin copies). `tests/property_apply_gate.rs` generalises these.

    use crate::ids::{Id, PeriodId, StudentId, SubjectId, WeekPatternId};
    use crate::ops::{
        AnnotatedOp, AnnotatedPeriodOp, AnnotatedStudentOp, AnnotatedSubjectOp, AssignmentOp, Op,
        PeriodOp, StudentOp, SubjectOp, WeekOp,
    };
    use crate::students::Student;
    use crate::subjects::Subject;
    use crate::week_patterns::WeekPattern;
    use crate::weeks::WeekDesc;
    use crate::{
        Data, FixableInvariant, InnerData, LogicError, PrecheckError, StudentPrecheckError,
    };
    use collomatique_state::InMemoryData;
    use std::collections::BTreeSet;

    /// Applies a (valid) op through the gate and returns its annotated form,
    /// so callers can read back the freshly issued ids.
    fn apply(data: &mut Data, op: Op) -> AnnotatedOp {
        let (annotated, _) = data.annotate(op);
        data.apply(&annotated).expect("valid op should apply");
        annotated
    }

    /// The smallest state where a student is referenced by an assignments row:
    /// one period, one subject running on it, one student assigned. Returns
    /// `(data, period, subject, student)`.
    fn data_with_assignment() -> (Data, PeriodId, SubjectId, StudentId) {
        let mut data = Data::default();
        let period = match apply(&mut data, Op::Period(PeriodOp::AddFront)) {
            AnnotatedOp::Period(AnnotatedPeriodOp::AddFront(p)) => p,
            other => panic!("unexpected annotated op {other:?}"),
        };
        let subject = match apply(
            &mut data,
            Op::Subject(SubjectOp::AddAfter(None, Subject::default())),
        ) {
            AnnotatedOp::Subject(AnnotatedSubjectOp::AddAfter(s, _, _)) => s,
            other => panic!("unexpected annotated op {other:?}"),
        };
        let student = match apply(&mut data, Op::Student(StudentOp::Add(Student::default()))) {
            AnnotatedOp::Student(AnnotatedStudentOp::Add(u, _)) => u,
            other => panic!("unexpected annotated op {other:?}"),
        };
        apply(
            &mut data,
            Op::Assignment(AssignmentOp::SetRow(
                period,
                subject,
                BTreeSet::from([student]),
            )),
        );
        (data, period, subject, student)
    }

    #[test]
    fn force_remove_referenced_student_lands_a_dangling_fk() {
        let (mut data, _period, _subject, student) = data_with_assignment();
        assert_eq!(
            data.get_inner_data().broken_invariants(),
            Ok(BTreeSet::new()),
            "the built state is valid"
        );

        // The Remove scans (colloscope / group-list / assignments / settings)
        // are stripped, so the forced removal succeeds even though the student
        // is still referenced by an assignments row.
        let (remove, _) = data.annotate(Op::Student(StudentOp::Remove(student)));
        data.force_apply(&remove)
            .expect("forced remove of a live student succeeds (scans stripped)");

        // The checker must see the now-dangling reference.
        let broken = data.get_inner_data().broken_invariants();
        assert!(
            matches!(&broken, Ok(set) if set.iter().any(|f| matches!(f, FixableInvariant::DanglingFk(_)))),
            "expected a dangling-FK report, got {broken:?}"
        );
    }

    #[test]
    fn force_add_on_existing_id_hard_errors_and_leaves_state_unchanged() {
        let (mut data, _period, _subject, student) = data_with_assignment();
        let before = data.clone();

        // A directly-built Add re-using a live id — the no-clobber carve-out is
        // kept, so this hard-errors without mutating.
        let dup = AnnotatedOp::Student(AnnotatedStudentOp::Add(student, Student::default()));
        let err = data.force_apply(&dup).unwrap_err();
        assert!(
            matches!(err, PrecheckError::Student(StudentPrecheckError::StudentIdAlreadyExists(id)) if id == student),
            "expected StudentIdAlreadyExists, got {err:?}"
        );
        assert!(
            data == before,
            "a failed force_apply must not mutate the state"
        );
    }

    #[test]
    fn force_update_on_dangling_target_hard_errors_and_leaves_state_unchanged() {
        let (mut data, _period, _subject, _student) = data_with_assignment();
        let before = data.clone();

        // Op-target existence is kept, so an Update on an absent id hard-errors.
        let ghost = unsafe { StudentId::new(9_999) };
        let update = AnnotatedOp::Student(AnnotatedStudentOp::Update(ghost, Student::default()));
        let err = data.force_apply(&update).unwrap_err();
        assert!(
            matches!(err, PrecheckError::Student(StudentPrecheckError::InvalidStudentId(id)) if id == ghost),
            "expected InvalidStudentId, got {err:?}"
        );
        assert!(
            data == before,
            "a failed force_apply must not mutate the state"
        );
    }

    #[test]
    fn force_global_update_drops_the_pre_gate_and_lands_an_invalid_state() {
        // A valid vehicle; its inner is replaced wholesale.
        let mut data = Data::default();

        // A corrupt inner: a student and a week pattern sharing the same raw id
        // — a duplicated-id LogicError that the apply gate rejects and rolls
        // back. `force_apply` has no gate, so the corrupt state lands.
        let mut corrupt = InnerData::default();
        let student = unsafe { StudentId::new(1) };
        let pattern = unsafe { WeekPatternId::new(1) };
        corrupt
            .params
            .students
            .student_map
            .insert(student, Student::default());
        corrupt.params.week_patterns.week_pattern_map.insert(
            pattern,
            WeekPattern {
                name: "P".into(),
                excluded_weeks: BTreeSet::new(),
            },
        );

        let op = AnnotatedOp::GlobalUpdate(corrupt);
        data.force_apply(&op)
            .expect("forced GlobalUpdate is infallible (no pre-gate)");

        assert_eq!(
            data.get_inner_data().broken_invariants(),
            Err(BTreeSet::from([LogicError::DuplicatedId(1)])),
            "the duplicated-id state is logically impossible"
        );
    }

    #[test]
    fn forced_valid_student_add_equals_apply() {
        let mut data = Data::default();
        let (add, _) = data.annotate(Op::Student(StudentOp::Add(Student::default())));

        let mut gated = data.clone();
        let mut forced = data.clone();
        let gated_rev = gated.apply(&add).expect("valid op");
        let forced_rev = forced.force_apply(&add).expect("valid op");

        assert_eq!(gated.get_inner_data(), forced.get_inner_data());
        assert_eq!(gated_rev, forced_rev);
    }

    #[test]
    fn forced_valid_week_add_equals_apply() {
        // Weeks exercise the copied helpers (`force_add_week` &c.), the highest
        // drift-risk spot (F2). Build a period, then compare the two paths on a
        // week AddFront.
        let mut data = Data::default();
        let period = match apply(&mut data, Op::Period(PeriodOp::AddFront)) {
            AnnotatedOp::Period(AnnotatedPeriodOp::AddFront(p)) => p,
            other => panic!("unexpected annotated op {other:?}"),
        };

        let (add_week, _) = data.annotate(Op::Week(WeekOp::AddFront(period, WeekDesc::default())));
        let mut gated = data.clone();
        let mut forced = data.clone();
        let gated_rev = gated.apply(&add_week).expect("valid op");
        let forced_rev = forced.force_apply(&add_week).expect("valid op");

        assert_eq!(gated.get_inner_data(), forced.get_inner_data());
        assert_eq!(gated_rev, forced_rev);
    }
}

#[cfg(test)]
mod apply_tests {
    //! Step-5 commit 1 pins for [Data::apply]: the apply/check/rollback gate
    //! rolls a broken landing back to a bit-identical pre-op state and reports it
    //! precisely; a `GlobalUpdate` carrying logically impossible (duplicated-id)
    //! data comes back as [InvalidOp::Logic], rolled back.

    use crate::ids::{Id, PeriodId, StudentId, SubjectId, WeekPatternId};
    use crate::ops::{
        AnnotatedOp, AnnotatedPeriodOp, AnnotatedStudentOp, AnnotatedSubjectOp, AssignmentOp, Op,
        PeriodOp, StudentOp, SubjectOp,
    };
    use crate::students::Student;
    use crate::subjects::Subject;
    use crate::week_patterns::WeekPattern;
    use crate::{Data, Error, FixableInvariant, InnerData, InvalidOp, Reference, StudentRefSite};
    use collomatique_state::InMemoryData;
    use std::collections::BTreeSet;

    /// Applies a (valid) op through the gate and returns its annotated form,
    /// so callers can read back the freshly issued ids.
    fn apply(data: &mut Data, op: Op) -> AnnotatedOp {
        let (annotated, _) = data.annotate(op);
        data.apply(&annotated).expect("valid op should apply");
        annotated
    }

    /// The smallest state where a student is referenced by an assignments row:
    /// one period, one subject running on it, one student assigned. Returns
    /// `(data, period, subject, student)`.
    fn data_with_assignment() -> (Data, PeriodId, SubjectId, StudentId) {
        let mut data = Data::default();
        let period = match apply(&mut data, Op::Period(PeriodOp::AddFront)) {
            AnnotatedOp::Period(AnnotatedPeriodOp::AddFront(p)) => p,
            other => panic!("unexpected annotated op {other:?}"),
        };
        let subject = match apply(
            &mut data,
            Op::Subject(SubjectOp::AddAfter(None, Subject::default())),
        ) {
            AnnotatedOp::Subject(AnnotatedSubjectOp::AddAfter(s, _, _)) => s,
            other => panic!("unexpected annotated op {other:?}"),
        };
        let student = match apply(&mut data, Op::Student(StudentOp::Add(Student::default()))) {
            AnnotatedOp::Student(AnnotatedStudentOp::Add(u, _)) => u,
            other => panic!("unexpected annotated op {other:?}"),
        };
        apply(
            &mut data,
            Op::Assignment(AssignmentOp::SetRow(
                period,
                subject,
                BTreeSet::from([student]),
            )),
        );
        (data, period, subject, student)
    }

    #[test]
    fn apply_invariant_breaking_op_rolls_back_and_reports() {
        let (mut data, _period, _subject, student) = data_with_assignment();
        let before = data.clone();

        // Removing a still-referenced student lands a dangling assignments FK
        // (the Remove scans are stripped in `force_apply`); the gate must roll the
        // state back and report it as an Invariants error.
        let (remove, _) = data.annotate(Op::Student(StudentOp::Remove(student)));
        let err = data.apply(&remove).unwrap_err();

        match err {
            Error::BrokenInvariants(set) => assert!(
                set.iter()
                    .any(|f| matches!(f, FixableInvariant::DanglingFk(_))),
                "expected a dangling-FK report, got {set:?}"
            ),
            other => panic!("expected BrokenInvariants, got {other:?}"),
        }
        assert!(
            data == before,
            "a rolled-back apply must leave the state bit-identical"
        );
    }

    #[test]
    fn apply_global_update_with_duplicated_id_errors_logic_and_rolls_back() {
        let mut data = Data::default();
        let before = data.clone();

        // A corrupt inner: a student and a week pattern sharing raw id 1 — a
        // duplicated-id LogicError. Through the gate this rolls back and surfaces
        // as InvalidOp::Logic (post-sealing the only route into that arm).
        let mut corrupt = InnerData::default();
        let student = unsafe { StudentId::new(1) };
        let pattern = unsafe { WeekPatternId::new(1) };
        corrupt
            .params
            .students
            .student_map
            .insert(student, Student::default());
        corrupt.params.week_patterns.week_pattern_map.insert(
            pattern,
            WeekPattern {
                name: "P".into(),
                excluded_weeks: BTreeSet::new(),
            },
        );

        let op = AnnotatedOp::GlobalUpdate(corrupt);
        let err = data.apply(&op).unwrap_err();

        assert!(
            matches!(err, Error::InvalidOp(InvalidOp::Logic(ref set)) if !set.is_empty()),
            "expected a non-empty Logic error, got {err:?}"
        );
        assert!(
            data == before,
            "a rolled-back GlobalUpdate must leave the state bit-identical"
        );
    }

    #[test]
    fn apply_set_row_with_a_dead_payload_student_is_a_checker_rejection() {
        let (mut data, period, subject, student) = data_with_assignment();
        let before = data.clone();

        // A student id nobody holds. `SetRow` prechecks its *address* — the
        // `(period, subject)` key, which an empty payload would clear without
        // leaving the FK net anything to look at — and nothing else. The
        // payload students are op content: the op lands, the checker walks the
        // row it wrote, and the dangling reference is what stops it. This is
        // one tier down from where the payload sweep used to catch it, and it
        // is the same tier `ColloscopeOp::SetGroupList`'s placements have always
        // been reported at.
        let ghost = unsafe { StudentId::new(9_999) };
        let (set_row, _) = data.annotate(Op::Assignment(AssignmentOp::SetRow(
            period,
            subject,
            BTreeSet::from([student, ghost]),
        )));
        let err = data.apply(&set_row).unwrap_err();

        assert_eq!(
            err,
            Error::BrokenInvariants(BTreeSet::from([FixableInvariant::DanglingFk(
                Reference::Student {
                    target: ghost,
                    site: StudentRefSite::AssignmentsStudent { period, subject },
                }
            )])),
            "the dead payload student is reported by the FK net — and it is the \
             only break, since the convergence checks skip a student that does \
             not resolve"
        );
        assert!(
            data == before,
            "a rolled-back apply must leave the state bit-identical"
        );
    }
}

#[cfg(test)]
mod construction_boundary_tests {
    //! Pins for the [Data] construction boundary — the decode trust boundary of
    //! the design record's G.4. [Data::from_inner_data] is the one door through
    //! which data built *outside* this crate enters, so both of its rejection
    //! arms ([FromInnerDataError::Logic] and
    //! [FromInnerDataError::BrokenInvariants]) are load-bearing: a broken state
    //! must never exist outside the apply/check/rollback primitive. Both arms
    //! were constructed but never exercised before this module.
    //!
    //! The third test pins the [Data]-level companion of the checker, the
    //! id-issuer high-water assertion. It fires on the *accepted* path of the
    //! gate, so the only way to reach it is a [Data] whose issuer was never
    //! built from its own ids — which in turn needs the crate-private field, and
    //! is why this module is in-crate rather than in `tests/`.

    use crate::ids::{Id, SlotId, StudentId, SubjectId, TeacherId, WeekId};
    use crate::ops::{AnnotatedOp, AnnotatedStudentOp};
    use crate::slots::{Slot, Slots};
    use crate::students::Student;
    use crate::subjects::Subject;
    use crate::{Data, FromInnerDataError, IdIssuer, InnerData};
    use collomatique_state::InMemoryData;
    use std::collections::BTreeSet;

    /// A minimal well-formed slot on the given subject/teacher, mirroring the
    /// invariants-module fixture: no week pattern, Monday 8:00.
    fn test_slot(subject_id: SubjectId, teacher_id: TeacherId) -> Slot {
        Slot {
            subject_id,
            teacher_id,
            start_time: collomatique_time::SlotStart {
                weekday: chrono::Weekday::Mon.into(),
                start_time: collomatique_time::WholeMinuteTime::new(
                    chrono::NaiveTime::from_hms_opt(8, 0, 0).unwrap(),
                )
                .unwrap(),
            },
            extra_info: String::new(),
            week_pattern: None,
            cost: 0,
        }
    }

    #[test]
    fn from_inner_data_rejects_logically_impossible_data() {
        // A stored *empty* colloscope interrogation row: the canonical form of
        // "no interrogation there" is an absent row, so a present empty one is
        // logically impossible. No production surface can build it — hence the
        // `forge_*` door — but a hand-edited or hostile file can.
        let mut inner_data = InnerData::default();
        let slot = unsafe { SlotId::new(1) };
        let week = unsafe { WeekId::new(2) };
        inner_data
            .colloscope
            .forge_interrogation_row(slot, week, BTreeSet::new());

        let err = Data::from_inner_data(inner_data).unwrap_err();

        assert!(
            matches!(err, FromInnerDataError::Logic(ref set) if !set.is_empty()),
            "expected a non-empty Logic error, got {err:?}"
        );
    }

    #[test]
    fn from_inner_data_rejects_broken_invariants() {
        // One subject with one slot, and a teacher id that names nobody: a
        // dangling FK. Unlike the logic tier this one *is* fixable — but a
        // loaded file has no cascade behind it, so the load fails outright.
        let mut inner_data = InnerData::default();
        let subject = unsafe { SubjectId::new(1) };
        let slot = unsafe { SlotId::new(2) };
        let teacher = unsafe { TeacherId::new(3) };
        inner_data
            .params
            .subjects
            .ordered_subject_list
            .insert_at(0, subject, Subject::default())
            .expect("a fresh list has no id to clobber");
        inner_data.params.slots =
            Slots::from_subject_rows([(subject, vec![(slot, test_slot(subject, teacher))])])
                .expect("one slot cannot duplicate an id");

        let err = Data::from_inner_data(inner_data).unwrap_err();

        assert!(
            matches!(err, FromInnerDataError::BrokenInvariants(ref set) if !set.is_empty()),
            "expected a non-empty BrokenInvariants error, got {err:?}"
        );
    }

    #[test]
    #[should_panic(expected = "not greater than all internal ids")]
    fn an_issuer_lagging_behind_the_data_panics_on_the_accepted_path() {
        // `from_inner_data` builds the issuer *from* the data's ids, so it can
        // never produce this pairing; the struct literal is the only route, and
        // it stands in for the real trigger named in [Data::apply]'s doc — an
        // `AnnotatedOp` transplanted from another `Data` instance, whose ids
        // this issuer never handed out.
        let mut inner_data = InnerData::default();
        let student = unsafe { StudentId::new(5) };
        inner_data
            .params
            .students
            .student_map
            .insert(student, Student::default());

        let mut data = Data {
            id_issuer: IdIssuer::new(std::iter::empty()).expect("an empty issuer is valid"),
            inner_data,
        };

        // A valid op on a valid document: the precheck passes, the landing
        // breaks nothing, and the gate reaches its `Ok` arm — where the
        // high-water assertion catches the lagging issuer.
        let op = AnnotatedOp::Student(AnnotatedStudentOp::Update(student, Student::default()));
        let _ = data.apply(&op);
    }
}
