//! Colloscopes state crate
//!
//! This crate implements the various concepts of [collomatique-state]
//! and the various traits for the specific case of colloscope representation.
//!

use serde::{Deserialize, Serialize};
use thiserror::Error;

use collomatique_state::{InMemoryData, Operation, tools};
use std::collections::BTreeMap;
use std::collections::BTreeSet;

/// Internal re-export of the generic table containers.
///
/// Tables are an implementation detail of this crate: consumers read them
/// through the inherent read API (`get`/`contains`/`iter`/`keys`/`values`/
/// `get_at`/…) and build their own copy with an explicit
/// `.iter().map(…).collect()` into a plain `BTreeMap`/`Vec` when they need one.
/// Kept `pub(crate)` so the path does not leak.
pub(crate) use collomatique_state::{OrderedTable, Table};

pub mod ids;
use ids::Id;
use ids::IdIssuer;
pub use ids::{
    GroupListId, IncompatId, NewId, PairingRuleId, PeriodId, SlotId, SlotPairingRuleId, StudentId,
    SubjectId, TeacherId, WeekId, WeekPatternId,
};
pub mod ops;
pub use ops::{
    AnnotatedOp, AssignmentOp, BalancingOp, ColloscopeOp, ExportConfigOp, GroupListOp, IncompatOp,
    Op, PairingOp, PeriodOp, SettingsOp, SlotOp, SlotPairingOp, StudentOp, SubjectOp, TeacherOp,
    WeekOp, WeekPatternOp,
};
pub use subjects::{
    Subject, SubjectInterrogationParameters, SubjectParameters, SubjectPeriodicity,
};

pub mod assignments;
pub mod balancing;
pub mod colloscope_params;
pub mod colloscopes;
pub mod export_config;
pub mod group_lists;
pub mod incompats;
pub mod invariants;
pub mod non_empty_range;
pub mod pairings;
pub mod periods;
pub mod refs;
pub mod settings;
pub mod slot_pairings;
pub mod slots;
pub mod soft_param;
pub mod students;
pub mod subjects;
pub mod teachers;
pub mod week_patterns;

pub use assignments::AssignmentError;
pub use balancing::BalancingError;
pub use colloscope_params::InvariantError;
pub use colloscopes::ColloscopeError;
pub use export_config::ExportConfigError;
pub use group_lists::GroupListError;
pub use incompats::IncompatError;
pub use invariants::{Convergence, FixableInvariant, LogicError};
pub use non_empty_range::{EmptyRangeError, NonEmptyRangeInclusive};
pub use pairings::PairingError;
pub use periods::PeriodError;
pub use periods::WeekError;
pub use settings::SettingsError;
pub use slot_pairings::SlotPairingError;
pub use slots::SlotError;
pub use students::StudentError;
pub use subjects::SubjectError;
pub use teachers::TeacherError;
pub use week_patterns::WeekPatternError;

pub use refs::{
    GroupListRefSite, PeriodRefSite, RefVisitor, Reference, SlotRefSite, StudentRefSite,
    SubjectRefSite, TeacherRefSite, WeekPatternRefSite, WeekRefSite,
};

// Joined views generated by `#[derive(Join)]` on the entity structs — the
// reference-based read shape (every FK resolved to a borrow of its entity).
pub use incompats::JoinedIncompatibility;
pub use pairings::{JoinedPairingRule, JoinedRulePart};
pub use slot_pairings::{JoinedSlotPairingRule, JoinedSlotRulePart};
pub use slots::JoinedSlot;
pub use students::JoinedStudent;
pub use subjects::JoinedSubject;
pub use teachers::JoinedTeacher;

/// Description of a person with contacts
///
/// This type is used to describe both students and teachers.
/// Each student and teacher has its own card with name and contacts.
/// There are not used for the colloscope solving process
/// but can help produce a nice colloscope output with contact info.
#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct PersonWithContact {
    /// Surname of the person
    ///
    /// Though this field can be an empty string,
    /// it is considered mandatory internally
    pub surname: String,

    /// Firstname of the person
    ///
    /// Though this field can be an empty string,
    /// it is considered mandatory internally
    pub firstname: String,

    /// Person's telephone number
    ///
    /// This field is optional: this reflects the
    /// fact that some persons might not want to share
    /// their personal info or only some of it.
    pub tel: Option<non_empty_string::NonEmptyString>,

    /// Person's email
    ///
    /// This field is optional: this reflects the
    /// fact that some persons might not want to share
    /// their personal info or only some of it.
    pub email: Option<non_empty_string::NonEmptyString>,
}

/// Internal structure to store the data for [Data]
///
/// We have `data1 == data2` if and only if their internal
/// data is the same. This means they would lead to the same
/// file on disk. But the internal id issuer might have a different
/// state.
///
/// [InnerData] represents this actual 'on-disk' data so we can
/// directly use `derive(PartialEq, Eq)` with it. The implementation
/// of [Eq] and [PartialEq] for [Data] relies on it.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct InnerData {
    pub params: colloscope_params::Parameters,
    pub colloscope: colloscopes::Colloscope,
    pub export_config: export_config::ExportConfig,
}

#[derive(Debug, Error, PartialEq, Eq, Clone)]
pub enum InnerDataError {
    #[error("Duplicate ids")]
    DuplicateIds,
    #[error("Error in paramters: {0}")]
    Params(#[from] InvariantError),
    #[error("Error in colloscope: {0}")]
    ColloscopeError(#[from] ColloscopeError),
}

impl InnerData {
    fn ids(&self) -> impl Iterator<Item = u64> {
        self.params.ids()
    }

    fn check_no_duplicate_ids(&self) -> bool {
        let mut ids_so_far = BTreeSet::new();

        for id in self.ids() {
            if !ids_so_far.insert(id) {
                return false;
            }
        }

        true
    }

    pub fn check_invariants(&self) -> Result<(), InnerDataError> {
        if !self.check_no_duplicate_ids() {
            return Err(InnerDataError::DuplicateIds);
        }

        self.params.check_invariants()?;
        self.colloscope.validate_against_params(&self.params)?;

        Ok(())
    }
}

/// Complete data that can be handled in the colloscope
///
/// This [Data] structure contains all the data that can
/// be manipulated in collomatique. It contains the list
/// of students, of teachers, the various interrogations,
/// a description of constraints etc. It also contains the
/// various colloscopes that have been generated or edited.
///
/// It cannot be modified or accessed directly. To the other
/// crates, this is an opaque type.
///
/// It does not necesserally correlate exactly to the data stored
/// on disk. This is to allow versioning.
#[derive(Debug)]
pub struct Data {
    id_issuer: std::sync::Mutex<IdIssuer>,
    inner_data: InnerData,
}

impl Clone for Data {
    fn clone(&self) -> Self {
        let guard = self.id_issuer.lock().unwrap();

        let id_issuer = guard.clone();
        Data {
            id_issuer: std::sync::Mutex::new(id_issuer),
            inner_data: self.inner_data.clone(),
        }
    }
}

impl PartialEq for Data {
    fn eq(&self, other: &Self) -> bool {
        self.inner_data == other.inner_data
    }
}

impl Eq for Data {}

/// Errors for colloscopes modification
///
/// These errors can be returned when trying to modify [Data].
#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum Error {
    #[error(transparent)]
    Student(#[from] StudentError),
    #[error(transparent)]
    Period(#[from] PeriodError),
    #[error(transparent)]
    Week(#[from] WeekError),
    #[error(transparent)]
    Subject(#[from] SubjectError),
    #[error(transparent)]
    Teacher(#[from] TeacherError),
    #[error(transparent)]
    Assignment(#[from] AssignmentError),
    #[error(transparent)]
    WeekPattern(#[from] WeekPatternError),
    #[error(transparent)]
    Slot(#[from] SlotError),
    #[error(transparent)]
    Incompat(#[from] IncompatError),
    #[error(transparent)]
    GroupList(#[from] GroupListError),
    #[error(transparent)]
    Settings(#[from] SettingsError),
    #[error(transparent)]
    Pairing(#[from] PairingError),
    #[error(transparent)]
    SlotPairing(#[from] SlotPairingError),
    #[error(transparent)]
    Balancing(#[from] BalancingError),
    #[error(transparent)]
    Colloscope(#[from] ColloscopeError),
    #[error(transparent)]
    ExportConfig(#[from] ExportConfigError),
    #[error(transparent)]
    GlobalUpdate(#[from] InnerDataError),
}

/// Errors for IDs
#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum FromInnerDataError {
    #[error(transparent)]
    IdError(#[from] tools::IdError),
    #[error(transparent)]
    InnerDataError(#[from] InnerDataError),
}

impl InMemoryData for Data {
    type OriginalOperation = Op;
    type AnnotatedOperation = AnnotatedOp;
    type NewInfo = Option<NewId>;
    type Error = Error;

    fn annotate(&self, op: Op) -> (AnnotatedOp, Option<NewId>) {
        let mut guard = self.id_issuer.lock().unwrap();
        AnnotatedOp::annotate(op, &mut guard)
    }

    fn apply(
        &mut self,
        op: &Self::AnnotatedOperation,
    ) -> std::result::Result<Self::AnnotatedOperation, Self::Error> {
        let backward = match op {
            AnnotatedOp::Student(student_op) => {
                AnnotatedOp::Student(self.apply_student(student_op)?)
            }
            AnnotatedOp::Period(period_op) => AnnotatedOp::Period(self.apply_period(period_op)?),
            AnnotatedOp::Week(week_op) => AnnotatedOp::Week(self.apply_week(week_op)?),
            AnnotatedOp::Subject(subject_op) => {
                AnnotatedOp::Subject(self.apply_subject(subject_op)?)
            }
            AnnotatedOp::Teacher(teacher_op) => {
                AnnotatedOp::Teacher(self.apply_teacher(teacher_op)?)
            }
            AnnotatedOp::Assignment(assignment_op) => {
                AnnotatedOp::Assignment(self.apply_assignment(assignment_op)?)
            }
            AnnotatedOp::WeekPattern(week_pattern_op) => {
                AnnotatedOp::WeekPattern(self.apply_week_pattern(week_pattern_op)?)
            }
            AnnotatedOp::Slot(slot_op) => AnnotatedOp::Slot(self.apply_slot(slot_op)?),
            AnnotatedOp::Incompat(incompat_op) => {
                AnnotatedOp::Incompat(self.apply_incompat(incompat_op)?)
            }
            AnnotatedOp::Pairing(pairing_op) => {
                AnnotatedOp::Pairing(self.apply_pairing(pairing_op)?)
            }
            AnnotatedOp::SlotPairing(slot_pairing_op) => {
                AnnotatedOp::SlotPairing(self.apply_slot_pairing(slot_pairing_op)?)
            }
            AnnotatedOp::GroupList(group_list_op) => {
                AnnotatedOp::GroupList(self.apply_group_list(group_list_op)?)
            }
            AnnotatedOp::Settings(settings_op) => {
                AnnotatedOp::Settings(self.apply_settings(settings_op)?)
            }
            AnnotatedOp::Balancing(balancing_op) => {
                AnnotatedOp::Balancing(self.apply_balancing(balancing_op)?)
            }
            AnnotatedOp::Colloscope(colloscope_op) => {
                AnnotatedOp::Colloscope(self.apply_colloscope(colloscope_op)?)
            }
            AnnotatedOp::ExportConfig(export_config_op) => {
                AnnotatedOp::ExportConfig(self.apply_export_config(export_config_op)?)
            }
            AnnotatedOp::GlobalUpdate(new_inner_data) => {
                new_inner_data.check_invariants()?;
                let old = std::mem::replace(&mut self.inner_data, new_inner_data.clone());
                AnnotatedOp::GlobalUpdate(old)
            }
        };
        self.check_invariants();
        Ok(backward)
    }
}

impl Data {
    /// USED INTERNALLY
    ///
    /// Checks all the invariants of data
    fn check_invariants(&self) {
        let max_id = self.inner_data.ids().max();

        if let Some(id) = max_id {
            let guard = self.id_issuer.lock().expect("No error on lock");
            if id >= guard.get_internal_counter() {
                panic!("IdIssuer internal counter is not greater than all internal ids");
            }
        }

        self.inner_data
            .check_invariants()
            .expect("Invariants should be valid in Data");
    }
}

impl Default for Data {
    fn default() -> Self {
        Self::new()
    }
}

impl Data {
    /// Create a new [Data]
    ///
    /// This [Data] is basically empty and corresponds to the
    /// state of a new file
    pub fn new() -> Data {
        Self::from_inner_data(InnerData::default()).expect("Default data should be valid")
    }

    /// Create a new [Data] from existing data
    ///
    /// This will check the consistency of the data
    /// and will also do some internal checks, so this might fail.
    pub fn from_inner_data(inner_data: InnerData) -> Result<Data, FromInnerDataError> {
        inner_data.check_invariants()?;

        let id_issuer = IdIssuer::new(inner_data.ids())?;

        let data = Data {
            id_issuer: std::sync::Mutex::new(id_issuer),
            inner_data,
        };

        data.check_invariants();

        Ok(data)
    }

    /// Returns a non-mutable reference to internal data
    ///
    /// Elementary ops allow the edition of data. But between two ops
    /// you can inspect the current data via this function
    pub fn get_inner_data(&self) -> &InnerData {
        &self.inner_data
    }

    /// Similar to [Self::get_inner_data] but consumes the [Data] and returns
    /// an owned [InnerData]
    pub fn into_inner_data(self) -> InnerData {
        self.inner_data
    }
}
