[package]
name = "collomatique-rpc"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
ordered-float = { workspace = true, features = ["serde"] }
anyhow.workspace = true
thiserror.workspace = true
collomatique-state-colloscopes = { path = "../state-colloscopes" }
collomatique-storage = { path = "../storage" }
collomatique-ilp = { path = "../ilp", features = ["serde"] }
collomatique-time = { path = "../time" }
