[package]
name = "collo-ml"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
pest.workspace = true
pest_derive = "2.8"
thiserror.workspace = true
collomatique-ilp = { path = "../ilp" }
collomatique-ilp-modeler = { path = "../ilp-modeler", default-features = false }
regex = "*"
collo-ml-derive = { path = "../collo-ml-derive" }
sha2 = "0.10"
base64 = "0.22"
lazy_static = "*"
derivative = "*"
ordered-float.workspace = true
sqlx.workspace = true
tokio = { workspace = true, features = ["sync", "rt-multi-thread"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }