//! Join module
//!
//! This module is the runtime side of the join machinery: turning
//! foreign keys into borrows of the entities they point to, resolved
//! against a context (typically the state data itself).
//!
//! The design is reference-based: joining never clones entities, it
//! borrows them straight out of the context.

/// Types that have a joined shape
///
/// This trait only declares *what* joining produces; the actual
/// resolution against a context happens in [`Join`]. Splitting the two
/// keeps the joined shape (and the error type) independent of any
/// particular context.
///
/// Leaf implementations on ID types come from the `EntityId` derive
/// (through its `#[entity(Type)]` attribute) with `Output<'a> = &'a Entity`
/// and `Error = Self` — the dangling ID is the diagnostic. Container
/// lifts for [`Option`], [`Vec`] and [`std::collections::BTreeSet`] are
/// provided below. Struct implementations come from the `Join` derive.
pub trait Joinable {
    /// The joined shape, borrowing from the context (and from `self`)
    type Output<'a>
    where
        Self: 'a;
    /// Error returned when a foreign key dangles
    type Error;
}

/// Types that can be joined against a context `Ctx`
///
/// Resolution is fail-fast: the first dangling foreign key aborts the
/// join and is reported through [`Joinable::Error`].
pub trait Join<Ctx>: Joinable {
    /// Resolve every foreign key against `ctx`, borrowing the entities
    fn join<'a>(&'a self, ctx: &'a Ctx) -> Result<Self::Output<'a>, Self::Error>;
}

/// Contexts that can resolve IDs of type `I` into entities
///
/// This is the only thing a context must provide for the leaf `Join`
/// implementations generated by `#[entity(Type)]`; it also insulates
/// consumers from where the entities actually live.
pub trait Lookup<I> {
    /// The entity type the IDs point to
    type Entity;

    /// Resolve `id`, or `None` if it dangles
    fn lookup(&self, id: I) -> Option<&Self::Entity>;
}

impl<T: Joinable> Joinable for Option<T> {
    type Output<'a>
        = Option<T::Output<'a>>
    where
        Self: 'a;
    type Error = T::Error;
}

impl<Ctx, T: Join<Ctx>> Join<Ctx> for Option<T> {
    fn join<'a>(&'a self, ctx: &'a Ctx) -> Result<Self::Output<'a>, Self::Error> {
        match self {
            Some(value) => Ok(Some(value.join(ctx)?)),
            None => Ok(None),
        }
    }
}

impl<T: Joinable> Joinable for Vec<T> {
    type Output<'a>
        = Vec<T::Output<'a>>
    where
        Self: 'a;
    type Error = T::Error;
}

impl<Ctx, T: Join<Ctx>> Join<Ctx> for Vec<T> {
    fn join<'a>(&'a self, ctx: &'a Ctx) -> Result<Self::Output<'a>, Self::Error> {
        self.iter().map(|value| value.join(ctx)).collect()
    }
}

/// Joined entities are usually not `Ord`, so a set of IDs joins into a
/// [`Vec`]; iteration follows the set order (= ID order), so the output
/// is deterministic.
impl<T: Joinable> Joinable for std::collections::BTreeSet<T> {
    type Output<'a>
        = Vec<T::Output<'a>>
    where
        Self: 'a;
    type Error = T::Error;
}

impl<Ctx, T: Join<Ctx>> Join<Ctx> for std::collections::BTreeSet<T> {
    fn join<'a>(&'a self, ctx: &'a Ctx) -> Result<Self::Output<'a>, Self::Error> {
        self.iter().map(|value| value.join(ctx)).collect()
    }
}
