[package]
name = "collomatique-state"
version = "0.1.0"
edition = "2021"

[dependencies]
collomatique-solver = { path = "../solver" }
collomatique-solver-colloscopes = { path = "../solver-colloscopes" }
thiserror = "1.0"
