[package]
name = "collomatique-state"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
default = ["derive"]
derive = ["dep:collomatique-state-derive"]

[dependencies]
collomatique-state-derive = { path = "../state-derive", optional = true }
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
