[package]
name = "collomatique-state"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
default = ["derive"]
derive = ["dep:collomatique-state-derive"]

[dependencies]
collomatique-state-derive = { path = "../state-derive", optional = true }
thiserror.workspace = true
