[package]
name = "collomatique-gtk4"
version = "0.1.0"
edition = "2021"

[dependencies]
collomatique-core = { path = "../core" }
relm4 = { version = "0.9", features = [ "libadwaita" ] }
clap = { version = "4.5", features = ["derive"] }
