//! The documents the property walks start from, and the test that writes them
//!
//! Every walk in this package used to begin at `harness::bootstrap`: a small
//! random document of a handful of students. Measured over 2810 probes, that
//! start plans 1331 group-list specs and **every one of them is a single
//! group** — the greedy's placement search is never exercised, and a mutation
//! that reverses its balanced targets leaves the walks green.
//!
//! The cause is not the walk length, and a longer walk does not fix it. Over
//! 3000 ops from a 25-student bootstrap, every one of the ~260 assignment ops
//! applies — and the document still ends with four assignment rows of one
//! student each. `gen_assignment` moves one student at a time, while a single
//! period or subject removal wipes a whole row, and the walk lands about 100
//! period removals and 200 subject ops in the same 3000. Rows are destroyed
//! faster than they can be built.
//!
//! What *does* survive is a row that arrives already full: hogwarts' 24 rows
//! of 24 students come out of the same 3000-op walk as 25 rows of 25. So a
//! fixture-grade document has to start with its assignment rows populated,
//! which is what [BootstrapScale::assigned_fraction] is for, and the walk's
//! job is to add everything a bootstrap has no ops for — slots, week patterns,
//! incompatibilities, group lists, a colloscope.
//!
//! So the walks are given big documents to start from, and this file is where
//! they come from. The four fixtures under `tests/fixtures/` are committed
//! data, regenerated by hand through the `#[ignore]` test below; the second
//! test is their rot guard.
//!
//! **Why fixtures and not a live read of `examples/`.** `start_hogwarts` is a
//! copy of `examples/hogwarts.collomatique`, and it is a *copy* on purpose.
//! `examples/` is user-facing content with its own reasons to change — a new
//! feature demo, a fix to a caveat. Read live, an edit there would silently
//! change the starting document of six fuzz walks: coverage could drop with
//! nothing going red, or a walk could go red for a reason unrelated to the
//! commit that broke it. A test pins its own input. This is not in tension
//! with `greedy-groups/tests/examples_build.rs`, which reads `examples/`
//! live on purpose: *checking the examples* is what that test is for, whereas
//! here hogwarts is only a conveniently realistic document.
//!
//! **On the `#[ignore]`.** `property_content_ord.rs:52` and `property_ops.rs`
//! record a decision of "no environment variables, no `#[ignore]` tiers" —
//! that is about what a walk *does when it runs*, and it still holds: one
//! hardcoded const per walk, the `fuzz` feature the only knob. An `#[ignore]`
//! test that rewrites a committed data file is a different thing, and it is
//! the shape `storage/tests/populated_round_trip.rs:107` already uses for its
//! golden fixture.

use std::path::PathBuf;

use collomatique_testgen_colloscopes::rand::{Rng, SeedableRng};
use collomatique_testgen_colloscopes::{ChaCha8Rng, generator, harness};

use collomatique_state::AppState;
use collomatique_state::traits::Manager;
use collomatique_state_colloscopes::{Data, InnerData};
use collomatique_storage::{deserialize_data, serialize_data};

use harness::BootstrapScale;

/// The four committed start documents
///
/// The first is hogwarts round-tripped; the other three are walked from a big
/// bootstrap, from another big bootstrap, and from hogwarts itself.
const FIXTURES: [&str; 4] = [
    "start_hogwarts.collomatique",
    "start_grown_0.collomatique",
    "start_grown_1.collomatique",
    "start_grown_hogwarts.collomatique",
];

/// How big a bootstrap the two `start_grown_*` fixtures are grown from
///
/// Sized to be comparable to hogwarts (24 students, 8 subjects, 24 assignment
/// rows), because the per-op cost of a walk grows with the document and
/// hogwarts is the size the walks' time budget was measured at. Big enough
/// that a row splits into several groups — the synthesized group-size ranges
/// top out at 5, so twenty students is four groups' worth — and no bigger.
const FIXTURE_SCALE: BootstrapScale = BootstrapScale {
    periods: 2..=3,
    students: 20..=30,
    subjects: 4..=6,
    teachers: 3..=5,
    // Not 1.0: rows of differing sizes are worth more to the greedy than a
    // document where every row is the whole class.
    assigned_fraction: Some(0.7),
};

/// Ops walked before a grown document is written out
///
/// Long enough to reach shapes a bootstrap alone never produces (slots, week
/// patterns, incompatibilities, group lists, a colloscope), while staying far
/// short of the length at which a big document would erode.
const GROW_OPS: usize = 3000;

/// A fixture may not be much heavier than hogwarts
///
/// This is a budget matter, not repo hygiene: the walks' measured cost per op
/// is a cost on a hogwarts-sized document, and a fixture twice that size would
/// carry a bigger multiplier than the budget assumes.
const MAX_FIXTURE_BYTES: usize = 2 * 52_359;

/// One line describing a document's shape, for the regeneration log
///
/// Printed *before* [assert_interesting] runs, so a regeneration that produces
/// a dud says what the dud looks like rather than only which rule it broke.
fn describe(inner: &InnerData, serialized: &str) -> String {
    let rows: Vec<usize> = inner
        .params
        .assignments
        .iter()
        .map(|(_period, _subject, students)| students.len())
        .collect();
    format!(
        "{} bytes, {} students, {} periods, {} subjects, {} assignment rows, \
         biggest row {}, {} group lists",
        serialized.len(),
        inner.params.students.student_map.iter().count(),
        inner.params.periods.ordered_period_list.iter().count(),
        inner.params.subjects.ordered_subject_list.iter().count(),
        rows.len(),
        rows.iter().copied().max().unwrap_or(0),
        inner.params.group_lists.group_list_map.iter().count(),
    )
}

/// This crate's `tests/fixtures/` directory
fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

/// Reads one committed fixture, as text
fn read_fixture(name: &str) -> String {
    let path = fixtures_dir().join(name);
    std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read the walk-start fixture {}: {e} — regenerate it with \
             `cargo test -p collomatique-property-tests --features fuzz \
             --test fixture_starts -- --ignored`",
            path.display(),
        )
    })
}

/// Walks [GROW_OPS] ops from a starting document and returns the result
///
/// `from` is `None` for a fresh bootstrap at [FIXTURE_SCALE], or the document
/// to shake up. Ops are drawn exactly as the walks draw them, with no invalid
/// fraction — a fixture is a *destination*, so there is nothing to gain from
/// ops designed to be rejected.
fn grow(seed: u64, from: Option<InnerData>) -> InnerData {
    let mut rng = ChaCha8Rng::seed_from_u64(seed);

    let mut state = match from {
        Some(inner) => AppState::<_, String>::new(
            Data::from_inner_data(inner).expect("a start document must pass the invariant gate"),
        ),
        None => harness::bootstrap_with(&mut rng, &FIXTURE_SCALE).0,
    };

    // The generator's replay pool, kept exactly as the walks keep it so the
    // op distribution is the walks' own.
    let mut snapshots: Vec<InnerData> = vec![state.get_data().get_inner_data().clone()];

    let mut successes = 0usize;
    for _ in 0..GROW_OPS {
        let (category, op) =
            generator::gen_op(&mut rng, state.get_data().get_inner_data(), &snapshots, 0.0);
        if state.apply(op, category.to_string()).is_ok() {
            successes += 1;
            if snapshots.len() < 8 && rng.random_bool(0.02) {
                snapshots.push(state.get_data().get_inner_data().clone());
            }
        }
    }
    assert!(
        successes * 2 >= GROW_OPS,
        "growing seed {seed}: only {successes}/{GROW_OPS} ops applied — the generator \
         degenerated into an error loop and the fixture is not a walked document",
    );

    // Dense ids keep the files small and make a regeneration diff readable
    // instead of a wall of shifted numbers.
    state.get_data().get_inner_data().clone().compact_ids()
}

/// What makes a start document worth walking from
///
/// Asserted when a fixture is generated, so a regeneration cannot silently
/// produce a dud, and again by the guard test below, so a committed fixture
/// cannot rot unnoticed.
fn assert_interesting(inner: &InnerData, serialized: &str, name: &str) {
    Data::from_inner_data(inner.clone())
        .unwrap_or_else(|e| panic!("{name}: a start document must pass the invariant gate: {e}"));

    let biggest_row = inner
        .params
        .assignments
        .iter()
        .map(|(_period, _subject, students)| students.len())
        .max()
        .unwrap_or(0);
    assert!(
        biggest_row >= 8,
        "{name}: the biggest assignment row holds {biggest_row} students — a start \
         document must have rows big enough to split into several groups",
    );

    let prefilled = inner
        .params
        .group_lists
        .group_list_map
        .iter()
        .filter(|(_, list)| list.is_prefilled())
        .count();
    assert!(
        prefilled > 0,
        "{name}: no prefilled group list — the walks need lists a request can keep",
    );

    assert!(
        serialized.len() <= MAX_FIXTURE_BYTES,
        "{name}: {} bytes, over the {MAX_FIXTURE_BYTES}-byte cap — the walks' time \
         budget was measured on a hogwarts-sized document",
        serialized.len(),
    );
}

/// Writes the four start fixtures
///
/// Run explicitly:
///
/// ```text
/// cargo test -p collomatique-property-tests --features fuzz \
///     --test fixture_starts -- --ignored
/// ```
///
/// then read the resulting documents' shape and diff before committing them.
/// This is the only place that reads `examples/`, and it never runs on its
/// own.
#[test]
#[ignore = "writes the walk-start fixtures; run explicitly to regenerate them"]
fn regenerate_walk_start_fixtures() {
    // Hogwarts goes through the same deserialize → compact → serialize path as
    // the three grown ones, so all four are uniform in format: a byte copy
    // would be left behind by a format migration that rewrites the others.
    let hogwarts_path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../examples/hogwarts.collomatique");
    let hogwarts_text = std::fs::read_to_string(&hogwarts_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", hogwarts_path.display()));
    let (hogwarts, caveats) = deserialize_data(&hogwarts_text)
        .unwrap_or_else(|e| panic!("cannot load {}: {e}", hogwarts_path.display()));
    assert!(
        caveats.is_empty(),
        "hogwarts must load without caveats, got {caveats:?}",
    );

    // Seeds 9 and 10 rather than 0 and 1: a walk ends with a *prefilled* group
    // list only about one time in six (measured over seeds 0–11, where only
    // those two qualified), because the generator mostly builds automatic
    // lists and student churn invalidates the prefilled ones. Both of these
    // also land a big assignment row, so nothing else was traded for it.
    let documents = [
        hogwarts.clone().compact_ids(),
        grow(9, None),
        grow(10, None),
        grow(2, Some(hogwarts)),
    ];

    for (name, inner) in FIXTURES.iter().zip(documents) {
        let serialized =
            serialize_data(&inner).unwrap_or_else(|e| panic!("cannot serialize {name}: {e}"));
        eprintln!("{name}: {}", describe(&inner, &serialized));
        assert_interesting(&inner, &serialized, name);

        let path = fixtures_dir().join(name);
        std::fs::write(&path, &serialized)
            .unwrap_or_else(|e| panic!("cannot write {}: {e}", path.display()));
    }
}

/// The committed fixtures still load, and are still worth walking from
///
/// Without this, a fixture could quietly stop being interesting — a format
/// migration that drops a section, a regeneration run with a bad seed — and
/// the walks would go back to brushing past the shapes they are meant to
/// cover, all of them green the whole way.
#[test]
fn walk_start_fixtures_are_interesting() {
    for name in FIXTURES {
        let text = read_fixture(name);
        let (inner, caveats) =
            deserialize_data(&text).unwrap_or_else(|e| panic!("cannot load {name}: {e}"));
        assert!(
            caveats.is_empty(),
            "{name} must load without caveats, got {caveats:?}",
        );
        assert_interesting(&inner, &text, name);
    }
}
