[package]
name = "collomatique-rpc-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
collomatique-rpc = { path = "../rpc" }
collomatique-python = { path = "../python" }
collomatique-state = { path = "../state" }
collomatique-state-colloscopes = { path = "../state-colloscopes" }
collomatique-ops = { path = "../ops" }
collomatique-constraints-colloscopes = { path = "../constraints-colloscopes" }
collomatique-ilp = { path = "../ilp" }
collomatique-sqlite-state = { path = "../sqlite-state" }
anyhow.workspace = true
tokio.workspace = true
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite"] }
