[package]
name = "collomatique-rpc-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
collomatique-rpc = { path = "../rpc" }
collomatique-python-runner = { path = "../python-runner" }
collomatique-state = { path = "../state" }
collomatique-state-colloscopes = { path = "../state-colloscopes" }
collomatique-constraints-colloscopes = { path = "../constraints-colloscopes" }
collomatique-ilp = { path = "../ilp", features = ["serde", "collo_cbc"] }
collomatique-ilp-modeler = { path = "../ilp-modeler", features = ["serde"] }
collomatique-strategies = { path = "../strategies" }
collomatique-subprocesses = { path = "../subprocesses" }
collomatique-time = { path = "../time" }
ordered-float.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
