[package]
name = "collomatique-constraints-colloscopes"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
collomatique-state-colloscopes = { path = "../state-colloscopes" }
collomatique-sqlite-state = { path = "../sqlite-state" }
collomatique-ilp = { path = "../ilp" }
collomatique-time = { path = "../time" }
collomatique-ilp-modeler = { path = "../ilp-modeler" }
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite"] }
ordered-float.workspace = true
